In [11]:
import pandas as pd
import numpy as np
import csv
import re
import matplotlib.pyplot as plt
%matplotlib inline

import dateutil.parser
from dateutil import parser
from datetime import datetime
df1 = pd.read_csv("http://web.mta.info/developers/data/nyct/turnstile/turnstile_170506.txt")
df2 = pd.read_csv("http://web.mta.info/developers/data/nyct/turnstile/turnstile_170513.txt")
df3 = pd.read_csv("http://web.mta.info/developers/data/nyct/turnstile/turnstile_170520.txt")
df4 = pd.read_csv("http://web.mta.info/developers/data/nyct/turnstile/turnstile_170527.txt")
df = pd.concat([df1, df2, df3, df4])
df = df.reset_index()
df = df.drop("index",1)
df['EXITS'] = df["EXITS                                                               "]
df.drop("EXITS                                                               ", axis = 1, inplace = True)
df

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/29/2017,00:00:00,REGULAR,6157740,2085315
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/29/2017,04:00:00,REGULAR,6157777,2085319
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/29/2017,08:00:00,REGULAR,6157810,2085353
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/29/2017,12:00:00,REGULAR,6157963,2085453
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/29/2017,16:00:00,REGULAR,6158212,2085529
5,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/29/2017,20:00:00,REGULAR,6158521,2085589
6,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/30/2017,00:00:00,REGULAR,6158637,2085612
7,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/30/2017,04:00:00,REGULAR,6158654,2085617
8,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/30/2017,08:00:00,REGULAR,6158661,2085641
9,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/30/2017,12:00:00,REGULAR,6158703,2085730
10,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/30/2017,16:00:00,REGULAR,6158797,2085785
11,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/30/2017,20:00:00,REGULAR,6159015,2085824
12,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/01/2017,00:00:00,REGULAR,6159107,2085842
13,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/01/2017,04:00:00,REGULAR,6159116,2085849
14,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/01/2017,08:00:00,REGULAR,6159166,2085976
15,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/01/2017,12:00:00,REGULAR,6159331,2086218
16,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/01/2017,16:00:00,REGULAR,6159595,2086299
17,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/01/2017,20:00:00,REGULAR,6160374,2086358
18,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/02/2017,00:00:00,REGULAR,6160508,2086374
19,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/02/2017,04:00:00,REGULAR,6160514,2086379
20,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/02/2017,08:00:00,REGULAR,6160555,2086499
21,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/02/2017,12:00:00,REGULAR,6160711,2086769
22,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/02/2017,16:00:00,REGULAR,6161012,2086835
23,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/02/2017,20:00:00,REGULAR,6161830,2086908
24,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/03/2017,00:00:00,REGULAR,6162061,2086933
25,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/03/2017,04:00:00,REGULAR,6162082,2086939
26,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/03/2017,08:00:00,REGULAR,6162129,2087070
27,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/03/2017,12:00:00,REGULAR,6162287,2087324
28,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/03/2017,16:00:00,REGULAR,6162575,2087391
29,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/03/2017,20:00:00,REGULAR,6163254,2087451
...,...,...,...,...,...,...,...,...,...,...,...
785059,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/22/2017,05:00:00,REGULAR,5554,299
785060,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/22/2017,09:00:00,REGULAR,5554,299
785061,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/22/2017,13:00:00,REGULAR,5554,299
785062,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/22/2017,17:00:00,REGULAR,5554,299
785063,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/22/2017,21:00:00,REGULAR,5554,299
785064,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/23/2017,01:00:00,REGULAR,5554,299
785065,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/23/2017,05:00:00,REGULAR,5554,299
785066,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/23/2017,08:18:52,REGULAR,5554,299
785067,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/23/2017,09:00:00,REGULAR,5554,299
785068,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/23/2017,13:00:00,REGULAR,5554,299
785069,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/23/2017,17:00:00,REGULAR,5554,299
785070,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/23/2017,21:00:00,REGULAR,5554,299
785071,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/24/2017,01:00:00,REGULAR,5554,299
785072,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/24/2017,05:00:00,REGULAR,5554,299
785073,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/24/2017,09:00:00,REGULAR,5554,299
785074,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/24/2017,13:00:00,REGULAR,5554,299
785075,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/24/2017,17:00:00,REGULAR,5554,299
785076,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/24/2017,21:00:00,REGULAR,5554,299
785077,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/25/2017,01:00:00,REGULAR,5554,299
785078,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/25/2017,05:00:00,REGULAR,5554,299
785079,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/25/2017,09:00:00,REGULAR,5554,299
785080,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/25/2017,13:00:00,REGULAR,5554,299
785081,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/25/2017,17:00:00,REGULAR,5554,299
785082,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/25/2017,21:00:00,REGULAR,5554,299
785083,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/26/2017,01:00:00,REGULAR,5554,299
785084,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/26/2017,05:00:00,REGULAR,5554,299
785085,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/26/2017,09:00:00,REGULAR,5554,299
785086,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/26/2017,13:00:00,REGULAR,5554,299
785087,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/26/2017,17:00:00,REGULAR,5554,299
785088,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/26/2017,21:00:00,REGULAR,5554,299

In [12]:
df['new_key'] = df[['C/A', 'UNIT', 'SCP', 'STATION']].apply(lambda x: ' '.join(x), axis=1)
df['date_time'] = (df[['DATE', 'TIME']].apply(lambda x: ' '.join(x), axis=1).str.replace('/','-'))
df['parsed_datetime'] = df.apply(lambda row: parser.parse(row.date_time), axis=1)
# df['date'] = (df['parsed_datetime'].apply(lambda x: x.date()))
# df['entries_num'] = int(df['ENTRIES'])-int(df['ENTRIES'][1:])
df

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS,new_key,date_time,parsed_datetime
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/29/2017,00:00:00,REGULAR,6157740,2085315,A002 R051 02-00-00 59 ST,04-29-2017 00:00:00,2017-04-29 00:00:00
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/29/2017,04:00:00,REGULAR,6157777,2085319,A002 R051 02-00-00 59 ST,04-29-2017 04:00:00,2017-04-29 04:00:00
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/29/2017,08:00:00,REGULAR,6157810,2085353,A002 R051 02-00-00 59 ST,04-29-2017 08:00:00,2017-04-29 08:00:00
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/29/2017,12:00:00,REGULAR,6157963,2085453,A002 R051 02-00-00 59 ST,04-29-2017 12:00:00,2017-04-29 12:00:00
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/29/2017,16:00:00,REGULAR,6158212,2085529,A002 R051 02-00-00 59 ST,04-29-2017 16:00:00,2017-04-29 16:00:00
5,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/29/2017,20:00:00,REGULAR,6158521,2085589,A002 R051 02-00-00 59 ST,04-29-2017 20:00:00,2017-04-29 20:00:00
6,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/30/2017,00:00:00,REGULAR,6158637,2085612,A002 R051 02-00-00 59 ST,04-30-2017 00:00:00,2017-04-30 00:00:00
7,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/30/2017,04:00:00,REGULAR,6158654,2085617,A002 R051 02-00-00 59 ST,04-30-2017 04:00:00,2017-04-30 04:00:00
8,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/30/2017,08:00:00,REGULAR,6158661,2085641,A002 R051 02-00-00 59 ST,04-30-2017 08:00:00,2017-04-30 08:00:00
9,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/30/2017,12:00:00,REGULAR,6158703,2085730,A002 R051 02-00-00 59 ST,04-30-2017 12:00:00,2017-04-30 12:00:00
10,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/30/2017,16:00:00,REGULAR,6158797,2085785,A002 R051 02-00-00 59 ST,04-30-2017 16:00:00,2017-04-30 16:00:00
11,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/30/2017,20:00:00,REGULAR,6159015,2085824,A002 R051 02-00-00 59 ST,04-30-2017 20:00:00,2017-04-30 20:00:00
12,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/01/2017,00:00:00,REGULAR,6159107,2085842,A002 R051 02-00-00 59 ST,05-01-2017 00:00:00,2017-05-01 00:00:00
13,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/01/2017,04:00:00,REGULAR,6159116,2085849,A002 R051 02-00-00 59 ST,05-01-2017 04:00:00,2017-05-01 04:00:00
14,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/01/2017,08:00:00,REGULAR,6159166,2085976,A002 R051 02-00-00 59 ST,05-01-2017 08:00:00,2017-05-01 08:00:00
15,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/01/2017,12:00:00,REGULAR,6159331,2086218,A002 R051 02-00-00 59 ST,05-01-2017 12:00:00,2017-05-01 12:00:00
16,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/01/2017,16:00:00,REGULAR,6159595,2086299,A002 R051 02-00-00 59 ST,05-01-2017 16:00:00,2017-05-01 16:00:00
17,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/01/2017,20:00:00,REGULAR,6160374,2086358,A002 R051 02-00-00 59 ST,05-01-2017 20:00:00,2017-05-01 20:00:00
18,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/02/2017,00:00:00,REGULAR,6160508,2086374,A002 R051 02-00-00 59 ST,05-02-2017 00:00:00,2017-05-02 00:00:00
19,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/02/2017,04:00:00,REGULAR,6160514,2086379,A002 R051 02-00-00 59 ST,05-02-2017 04:00:00,2017-05-02 04:00:00
20,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/02/2017,08:00:00,REGULAR,6160555,2086499,A002 R051 02-00-00 59 ST,05-02-2017 08:00:00,2017-05-02 08:00:00
21,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/02/2017,12:00:00,REGULAR,6160711,2086769,A002 R051 02-00-00 59 ST,05-02-2017 12:00:00,2017-05-02 12:00:00
22,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/02/2017,16:00:00,REGULAR,6161012,2086835,A002 R051 02-00-00 59 ST,05-02-2017 16:00:00,2017-05-02 16:00:00
23,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/02/2017,20:00:00,REGULAR,6161830,2086908,A002 R051 02-00-00 59 ST,05-02-2017 20:00:00,2017-05-02 20:00:00
24,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/03/2017,00:00:00,REGULAR,6162061,2086933,A002 R051 02-00-00 59 ST,05-03-2017 00:00:00,2017-05-03 00:00:00
25,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/03/2017,04:00:00,REGULAR,6162082,2086939,A002 R051 02-00-00 59 ST,05-03-2017 04:00:00,2017-05-03 04:00:00
26,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/03/2017,08:00:00,REGULAR,6162129,2087070,A002 R051 02-00-00 59 ST,05-03-2017 08:00:00,2017-05-03 08:00:00
27,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/03/2017,12:00:00,REGULAR,6162287,2087324,A002 R051 02-00-00 59 ST,05-03-2017 12:00:00,2017-05-03 12:00:00
28,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/03/2017,16:00:00,REGULAR,6162575,2087391,A002 R051 02-00-00 59 ST,05-03-2017 16:00:00,2017-05-03 16:00:00
29,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/03/2017,20:00:00,REGULAR,6163254,2087451,A002 R051 02-00-00 59 ST,05-03-2017 20:00:00,2017-05-03 20:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785059,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/22/2017,05:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-22-2017 05:00:00,2017-05-22 05:00:00
785060,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/22/2017,09:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-22-2017 09:00:00,2017-05-22 09:00:00
785061,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/22/2017,13:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-22-2017 13:00:00,2017-05-22 13:00:00
785062,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/22/2017,17:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-22-2017 17:00:00,2017-05-22 17:00:00
785063,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/22/2017,21:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-22-2017 21:00:00,2017-05-22 21:00:00
785064,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/23/2017,01:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-23-2017 01:00:00,2017-05-23 01:00:00
785065,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/23/2017,05:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-23-2017 05:00:00,2017-05-23 05:00:00
785066,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/23/2017,08:18:52,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-23-2017 08:18:52,2017-05-23 08:18:52
785067,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/23/2017,09:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-23-2017 09:00:00,2017-05-23 09:00:00
785068,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/23/2017,13:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-23-2017 13:00:00,2017-05-23 13:00:00
785069,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/23/2017,17:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-23-2017 17:00:00,2017-05-23 17:00:00
785070,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/23/2017,21:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-23-2017 21:00:00,2017-05-23 21:00:00
785071,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/24/2017,01:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-24-2017 01:00:00,2017-05-24 01:00:00
785072,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/24/2017,05:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-24-2017 05:00:00,2017-05-24 05:00:00
785073,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/24/2017,09:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-24-2017 09:00:00,2017-05-24 09:00:00
785074,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/24/2017,13:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-24-2017 13:00:00,2017-05-24 13:00:00
785075,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/24/2017,17:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-24-2017 17:00:00,2017-05-24 17:00:00
785076,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/24/2017,21:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-24-2017 21:00:00,2017-05-24 21:00:00
785077,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/25/2017,01:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-25-2017 01:00:00,2017-05-25 01:00:00
785078,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/25/2017,05:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-25-2017 05:00:00,2017-05-25 05:00:00
785079,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/25/2017,09:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-25-2017 09:00:00,2017-05-25 09:00:00
785080,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/25/2017,13:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-25-2017 13:00:00,2017-05-25 13:00:00
785081,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/25/2017,17:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-25-2017 17:00:00,2017-05-25 17:00:00
785082,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/25/2017,21:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-25-2017 21:00:00,2017-05-25 21:00:00
785083,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/26/2017,01:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-26-2017 01:00:00,2017-05-26 01:00:00
785084,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/26/2017,05:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-26-2017 05:00:00,2017-05-26 05:00:00
785085,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/26/2017,09:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-26-2017 09:00:00,2017-05-26 09:00:00
785086,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/26/2017,13:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-26-2017 13:00:00,2017-05-26 13:00:00
785087,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/26/2017,17:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-26-2017 17:00:00,2017-05-26 17:00:00
785088,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/26/2017,21:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-26-2017 21:00:00,2017-05-26 21:00:00

In [13]:
station_id = pd.Categorical(df['new_key']).codes
df['station_id'] = station_id
df

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS,new_key,date_time,parsed_datetime,station_id
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/29/2017,00:00:00,REGULAR,6157740,2085315,A002 R051 02-00-00 59 ST,04-29-2017 00:00:00,2017-04-29 00:00:00,0
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/29/2017,04:00:00,REGULAR,6157777,2085319,A002 R051 02-00-00 59 ST,04-29-2017 04:00:00,2017-04-29 04:00:00,0
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/29/2017,08:00:00,REGULAR,6157810,2085353,A002 R051 02-00-00 59 ST,04-29-2017 08:00:00,2017-04-29 08:00:00,0
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/29/2017,12:00:00,REGULAR,6157963,2085453,A002 R051 02-00-00 59 ST,04-29-2017 12:00:00,2017-04-29 12:00:00,0
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/29/2017,16:00:00,REGULAR,6158212,2085529,A002 R051 02-00-00 59 ST,04-29-2017 16:00:00,2017-04-29 16:00:00,0
5,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/29/2017,20:00:00,REGULAR,6158521,2085589,A002 R051 02-00-00 59 ST,04-29-2017 20:00:00,2017-04-29 20:00:00,0
6,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/30/2017,00:00:00,REGULAR,6158637,2085612,A002 R051 02-00-00 59 ST,04-30-2017 00:00:00,2017-04-30 00:00:00,0
7,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/30/2017,04:00:00,REGULAR,6158654,2085617,A002 R051 02-00-00 59 ST,04-30-2017 04:00:00,2017-04-30 04:00:00,0
8,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/30/2017,08:00:00,REGULAR,6158661,2085641,A002 R051 02-00-00 59 ST,04-30-2017 08:00:00,2017-04-30 08:00:00,0
9,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/30/2017,12:00:00,REGULAR,6158703,2085730,A002 R051 02-00-00 59 ST,04-30-2017 12:00:00,2017-04-30 12:00:00,0
10,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/30/2017,16:00:00,REGULAR,6158797,2085785,A002 R051 02-00-00 59 ST,04-30-2017 16:00:00,2017-04-30 16:00:00,0
11,A002,R051,02-00-00,59 ST,NQR456W,BMT,04/30/2017,20:00:00,REGULAR,6159015,2085824,A002 R051 02-00-00 59 ST,04-30-2017 20:00:00,2017-04-30 20:00:00,0
12,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/01/2017,00:00:00,REGULAR,6159107,2085842,A002 R051 02-00-00 59 ST,05-01-2017 00:00:00,2017-05-01 00:00:00,0
13,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/01/2017,04:00:00,REGULAR,6159116,2085849,A002 R051 02-00-00 59 ST,05-01-2017 04:00:00,2017-05-01 04:00:00,0
14,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/01/2017,08:00:00,REGULAR,6159166,2085976,A002 R051 02-00-00 59 ST,05-01-2017 08:00:00,2017-05-01 08:00:00,0
15,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/01/2017,12:00:00,REGULAR,6159331,2086218,A002 R051 02-00-00 59 ST,05-01-2017 12:00:00,2017-05-01 12:00:00,0
16,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/01/2017,16:00:00,REGULAR,6159595,2086299,A002 R051 02-00-00 59 ST,05-01-2017 16:00:00,2017-05-01 16:00:00,0
17,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/01/2017,20:00:00,REGULAR,6160374,2086358,A002 R051 02-00-00 59 ST,05-01-2017 20:00:00,2017-05-01 20:00:00,0
18,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/02/2017,00:00:00,REGULAR,6160508,2086374,A002 R051 02-00-00 59 ST,05-02-2017 00:00:00,2017-05-02 00:00:00,0
19,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/02/2017,04:00:00,REGULAR,6160514,2086379,A002 R051 02-00-00 59 ST,05-02-2017 04:00:00,2017-05-02 04:00:00,0
20,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/02/2017,08:00:00,REGULAR,6160555,2086499,A002 R051 02-00-00 59 ST,05-02-2017 08:00:00,2017-05-02 08:00:00,0
21,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/02/2017,12:00:00,REGULAR,6160711,2086769,A002 R051 02-00-00 59 ST,05-02-2017 12:00:00,2017-05-02 12:00:00,0
22,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/02/2017,16:00:00,REGULAR,6161012,2086835,A002 R051 02-00-00 59 ST,05-02-2017 16:00:00,2017-05-02 16:00:00,0
23,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/02/2017,20:00:00,REGULAR,6161830,2086908,A002 R051 02-00-00 59 ST,05-02-2017 20:00:00,2017-05-02 20:00:00,0
24,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/03/2017,00:00:00,REGULAR,6162061,2086933,A002 R051 02-00-00 59 ST,05-03-2017 00:00:00,2017-05-03 00:00:00,0
25,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/03/2017,04:00:00,REGULAR,6162082,2086939,A002 R051 02-00-00 59 ST,05-03-2017 04:00:00,2017-05-03 04:00:00,0
26,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/03/2017,08:00:00,REGULAR,6162129,2087070,A002 R051 02-00-00 59 ST,05-03-2017 08:00:00,2017-05-03 08:00:00,0
27,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/03/2017,12:00:00,REGULAR,6162287,2087324,A002 R051 02-00-00 59 ST,05-03-2017 12:00:00,2017-05-03 12:00:00,0
28,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/03/2017,16:00:00,REGULAR,6162575,2087391,A002 R051 02-00-00 59 ST,05-03-2017 16:00:00,2017-05-03 16:00:00,0
29,A002,R051,02-00-00,59 ST,NQR456W,BMT,05/03/2017,20:00:00,REGULAR,6163254,2087451,A002 R051 02-00-00 59 ST,05-03-2017 20:00:00,2017-05-03 20:00:00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785059,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/22/2017,05:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-22-2017 05:00:00,2017-05-22 05:00:00,4705
785060,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/22/2017,09:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-22-2017 09:00:00,2017-05-22 09:00:00,4705
785061,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/22/2017,13:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-22-2017 13:00:00,2017-05-22 13:00:00,4705
785062,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/22/2017,17:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-22-2017 17:00:00,2017-05-22 17:00:00,4705
785063,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/22/2017,21:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-22-2017 21:00:00,2017-05-22 21:00:00,4705
785064,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/23/2017,01:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-23-2017 01:00:00,2017-05-23 01:00:00,4705
785065,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/23/2017,05:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-23-2017 05:00:00,2017-05-23 05:00:00,4705
785066,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/23/2017,08:18:52,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-23-2017 08:18:52,2017-05-23 08:18:52,4705
785067,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/23/2017,09:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-23-2017 09:00:00,2017-05-23 09:00:00,4705
785068,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/23/2017,13:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-23-2017 13:00:00,2017-05-23 13:00:00,4705
785069,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/23/2017,17:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-23-2017 17:00:00,2017-05-23 17:00:00,4705
785070,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/23/2017,21:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-23-2017 21:00:00,2017-05-23 21:00:00,4705
785071,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/24/2017,01:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-24-2017 01:00:00,2017-05-24 01:00:00,4705
785072,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/24/2017,05:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-24-2017 05:00:00,2017-05-24 05:00:00,4705
785073,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/24/2017,09:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-24-2017 09:00:00,2017-05-24 09:00:00,4705
785074,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/24/2017,13:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-24-2017 13:00:00,2017-05-24 13:00:00,4705
785075,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/24/2017,17:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-24-2017 17:00:00,2017-05-24 17:00:00,4705
785076,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/24/2017,21:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-24-2017 21:00:00,2017-05-24 21:00:00,4705
785077,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/25/2017,01:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-25-2017 01:00:00,2017-05-25 01:00:00,4705
785078,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/25/2017,05:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-25-2017 05:00:00,2017-05-25 05:00:00,4705
785079,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/25/2017,09:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-25-2017 09:00:00,2017-05-25 09:00:00,4705
785080,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/25/2017,13:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-25-2017 13:00:00,2017-05-25 13:00:00,4705
785081,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/25/2017,17:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-25-2017 17:00:00,2017-05-25 17:00:00,4705
785082,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/25/2017,21:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-25-2017 21:00:00,2017-05-25 21:00:00,4705
785083,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/26/2017,01:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-26-2017 01:00:00,2017-05-26 01:00:00,4705
785084,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/26/2017,05:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-26-2017 05:00:00,2017-05-26 05:00:00,4705
785085,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/26/2017,09:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-26-2017 09:00:00,2017-05-26 09:00:00,4705
785086,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/26/2017,13:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-26-2017 13:00:00,2017-05-26 13:00:00,4705
785087,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/26/2017,17:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-26-2017 17:00:00,2017-05-26 17:00:00,4705
785088,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,05/26/2017,21:00:00,REGULAR,5554,299,TRAM2 R469 00-05-01 RIT-ROOSEVELT,05-26-2017 21:00:00,2017-05-26 21:00:00,4705

In [14]:
df.drop(['C/A', 'UNIT', 'SCP', 'DIVISION', 'new_key', 'DATE', 'TIME', 'date_time', 'DESC'], axis = 1, inplace = True)
df.sort_values(['station_id','parsed_datetime'], ascending=[True,True])
df

,STATION,LINENAME,ENTRIES,EXITS,parsed_datetime,station_id
0,59 ST,NQR456W,6157740,2085315,2017-04-29 00:00:00,0
1,59 ST,NQR456W,6157777,2085319,2017-04-29 04:00:00,0
2,59 ST,NQR456W,6157810,2085353,2017-04-29 08:00:00,0
3,59 ST,NQR456W,6157963,2085453,2017-04-29 12:00:00,0
4,59 ST,NQR456W,6158212,2085529,2017-04-29 16:00:00,0
5,59 ST,NQR456W,6158521,2085589,2017-04-29 20:00:00,0
6,59 ST,NQR456W,6158637,2085612,2017-04-30 00:00:00,0
7,59 ST,NQR456W,6158654,2085617,2017-04-30 04:00:00,0
8,59 ST,NQR456W,6158661,2085641,2017-04-30 08:00:00,0
9,59 ST,NQR456W,6158703,2085730,2017-04-30 12:00:00,0
10,59 ST,NQR456W,6158797,2085785,2017-04-30 16:00:00,0
11,59 ST,NQR456W,6159015,2085824,2017-04-30 20:00:00,0
12,59 ST,NQR456W,6159107,2085842,2017-05-01 00:00:00,0
13,59 ST,NQR456W,6159116,2085849,2017-05-01 04:00:00,0
14,59 ST,NQR456W,6159166,2085976,2017-05-01 08:00:00,0
15,59 ST,NQR456W,6159331,2086218,2017-05-01 12:00:00,0
16,59 ST,NQR456W,6159595,2086299,2017-05-01 16:00:00,0
17,59 ST,NQR456W,6160374,2086358,2017-05-01 20:00:00,0
18,59 ST,NQR456W,6160508,2086374,2017-05-02 00:00:00,0
19,59 ST,NQR456W,6160514,2086379,2017-05-02 04:00:00,0
20,59 ST,NQR456W,6160555,2086499,2017-05-02 08:00:00,0
21,59 ST,NQR456W,6160711,2086769,2017-05-02 12:00:00,0
22,59 ST,NQR456W,6161012,2086835,2017-05-02 16:00:00,0
23,59 ST,NQR456W,6161830,2086908,2017-05-02 20:00:00,0
24,59 ST,NQR456W,6162061,2086933,2017-05-03 00:00:00,0
25,59 ST,NQR456W,6162082,2086939,2017-05-03 04:00:00,0
26,59 ST,NQR456W,6162129,2087070,2017-05-03 08:00:00,0
27,59 ST,NQR456W,6162287,2087324,2017-05-03 12:00:00,0
28,59 ST,NQR456W,6162575,2087391,2017-05-03 16:00:00,0
29,59 ST,NQR456W,6163254,2087451,2017-05-03 20:00:00,0
...,...,...,...,...,...,...
785059,RIT-ROOSEVELT,R,5554,299,2017-05-22 05:00:00,4705
785060,RIT-ROOSEVELT,R,5554,299,2017-05-22 09:00:00,4705
785061,RIT-ROOSEVELT,R,5554,299,2017-05-22 13:00:00,4705
785062,RIT-ROOSEVELT,R,5554,299,2017-05-22 17:00:00,4705
785063,RIT-ROOSEVELT,R,5554,299,2017-05-22 21:00:00,4705
785064,RIT-ROOSEVELT,R,5554,299,2017-05-23 01:00:00,4705
785065,RIT-ROOSEVELT,R,5554,299,2017-05-23 05:00:00,4705
785066,RIT-ROOSEVELT,R,5554,299,2017-05-23 08:18:52,4705
785067,RIT-ROOSEVELT,R,5554,299,2017-05-23 09:00:00,4705
785068,RIT-ROOSEVELT,R,5554,299,2017-05-23 13:00:00,4705
785069,RIT-ROOSEVELT,R,5554,299,2017-05-23 17:00:00,4705
785070,RIT-ROOSEVELT,R,5554,299,2017-05-23 21:00:00,4705
785071,RIT-ROOSEVELT,R,5554,299,2017-05-24 01:00:00,4705
785072,RIT-ROOSEVELT,R,5554,299,2017-05-24 05:00:00,4705
785073,RIT-ROOSEVELT,R,5554,299,2017-05-24 09:00:00,4705
785074,RIT-ROOSEVELT,R,5554,299,2017-05-24 13:00:00,4705
785075,RIT-ROOSEVELT,R,5554,299,2017-05-24 17:00:00,4705
785076,RIT-ROOSEVELT,R,5554,299,2017-05-24 21:00:00,4705
785077,RIT-ROOSEVELT,R,5554,299,2017-05-25 01:00:00,4705
785078,RIT-ROOSEVELT,R,5554,299,2017-05-25 05:00:00,4705
785079,RIT-ROOSEVELT,R,5554,299,2017-05-25 09:00:00,4705
785080,RIT-ROOSEVELT,R,5554,299,2017-05-25 13:00:00,4705
785081,RIT-ROOSEVELT,R,5554,299,2017-05-25 17:00:00,4705
785082,RIT-ROOSEVELT,R,5554,299,2017-05-25 21:00:00,4705
785083,RIT-ROOSEVELT,R,5554,299,2017-05-26 01:00:00,4705
785084,RIT-ROOSEVELT,R,5554,299,2017-05-26 05:00:00,4705
785085,RIT-ROOSEVELT,R,5554,299,2017-05-26 09:00:00,4705
785086,RIT-ROOSEVELT,R,5554,299,2017-05-26 13:00:00,4705
785087,RIT-ROOSEVELT,R,5554,299,2017-05-26 17:00:00,4705
785088,RIT-ROOSEVELT,R,5554,299,2017-05-26 21:00:00,4705

In [99]:
df['entry_num'] = abs(df['ENTRIES'].diff())
df['exit_num'] = abs(df['EXITS'].diff())
df['station_diff'] = df['station_id'].diff()
df

,STATION,LINENAME,ENTRIES,EXITS,parsed_datetime,station_id,entry_num,exit_num,station_diff,time,Weekend,line_sort
0,59 ST,NQR456W,6157777,2085319,2017-04-29 04:00:00,0,NaN,NaN,NaN,04:00:00,True,456NQRW
1,59 ST,NQR456W,6157810,2085353,2017-04-29 08:00:00,0,33.0,34.0,0.0,08:00:00,True,456NQRW
2,59 ST,NQR456W,6157963,2085453,2017-04-29 12:00:00,0,153.0,100.0,0.0,12:00:00,True,456NQRW
3,59 ST,NQR456W,6158212,2085529,2017-04-29 16:00:00,0,249.0,76.0,0.0,16:00:00,True,456NQRW
4,59 ST,NQR456W,6158521,2085589,2017-04-29 20:00:00,0,309.0,60.0,0.0,20:00:00,True,456NQRW
5,59 ST,NQR456W,6158637,2085612,2017-04-30 00:00:00,0,116.0,23.0,0.0,00:00:00,True,456NQRW
6,59 ST,NQR456W,6158654,2085617,2017-04-30 04:00:00,0,17.0,5.0,0.0,04:00:00,True,456NQRW
7,59 ST,NQR456W,6158661,2085641,2017-04-30 08:00:00,0,7.0,24.0,0.0,08:00:00,True,456NQRW
8,59 ST,NQR456W,6158703,2085730,2017-04-30 12:00:00,0,42.0,89.0,0.0,12:00:00,True,456NQRW
9,59 ST,NQR456W,6158797,2085785,2017-04-30 16:00:00,0,94.0,55.0,0.0,16:00:00,True,456NQRW
10,59 ST,NQR456W,6159015,2085824,2017-04-30 20:00:00,0,218.0,39.0,0.0,20:00:00,True,456NQRW
11,59 ST,NQR456W,6159107,2085842,2017-05-01 00:00:00,0,92.0,18.0,0.0,00:00:00,False,456NQRW
12,59 ST,NQR456W,6159116,2085849,2017-05-01 04:00:00,0,9.0,7.0,0.0,04:00:00,False,456NQRW
13,59 ST,NQR456W,6159166,2085976,2017-05-01 08:00:00,0,50.0,127.0,0.0,08:00:00,False,456NQRW
14,59 ST,NQR456W,6159331,2086218,2017-05-01 12:00:00,0,165.0,242.0,0.0,12:00:00,False,456NQRW
15,59 ST,NQR456W,6159595,2086299,2017-05-01 16:00:00,0,264.0,81.0,0.0,16:00:00,False,456NQRW
16,59 ST,NQR456W,6160374,2086358,2017-05-01 20:00:00,0,779.0,59.0,0.0,20:00:00,False,456NQRW
17,59 ST,NQR456W,6160508,2086374,2017-05-02 00:00:00,0,134.0,16.0,0.0,00:00:00,False,456NQRW
18,59 ST,NQR456W,6160514,2086379,2017-05-02 04:00:00,0,6.0,5.0,0.0,04:00:00,False,456NQRW
19,59 ST,NQR456W,6160555,2086499,2017-05-02 08:00:00,0,41.0,120.0,0.0,08:00:00,False,456NQRW
20,59 ST,NQR456W,6160711,2086769,2017-05-02 12:00:00,0,156.0,270.0,0.0,12:00:00,False,456NQRW
21,59 ST,NQR456W,6161012,2086835,2017-05-02 16:00:00,0,301.0,66.0,0.0,16:00:00,False,456NQRW
22,59 ST,NQR456W,6161830,2086908,2017-05-02 20:00:00,0,818.0,73.0,0.0,20:00:00,False,456NQRW
23,59 ST,NQR456W,6162061,2086933,2017-05-03 00:00:00,0,231.0,25.0,0.0,00:00:00,False,456NQRW
24,59 ST,NQR456W,6162082,2086939,2017-05-03 04:00:00,0,21.0,6.0,0.0,04:00:00,False,456NQRW
25,59 ST,NQR456W,6162129,2087070,2017-05-03 08:00:00,0,47.0,131.0,0.0,08:00:00,False,456NQRW
26,59 ST,NQR456W,6162287,2087324,2017-05-03 12:00:00,0,158.0,254.0,0.0,12:00:00,False,456NQRW
27,59 ST,NQR456W,6162575,2087391,2017-05-03 16:00:00,0,288.0,67.0,0.0,16:00:00,False,456NQRW
28,59 ST,NQR456W,6163254,2087451,2017-05-03 20:00:00,0,679.0,60.0,0.0,20:00:00,False,456NQRW
29,59 ST,NQR456W,6163517,2087485,2017-05-04 00:00:00,0,263.0,34.0,0.0,00:00:00,False,456NQRW
...,...,...,...,...,...,...,...,...,...,...,...,...
766311,RIT-ROOSEVELT,R,5554,299,2017-05-22 05:00:00,4705,0.0,0.0,0.0,05:00:00,False,R
766312,RIT-ROOSEVELT,R,5554,299,2017-05-22 09:00:00,4705,0.0,0.0,0.0,09:00:00,False,R
766313,RIT-ROOSEVELT,R,5554,299,2017-05-22 13:00:00,4705,0.0,0.0,0.0,13:00:00,False,R
766314,RIT-ROOSEVELT,R,5554,299,2017-05-22 17:00:00,4705,0.0,0.0,0.0,17:00:00,False,R
766315,RIT-ROOSEVELT,R,5554,299,2017-05-22 21:00:00,4705,0.0,0.0,0.0,21:00:00,False,R
766316,RIT-ROOSEVELT,R,5554,299,2017-05-23 01:00:00,4705,0.0,0.0,0.0,01:00:00,False,R
766317,RIT-ROOSEVELT,R,5554,299,2017-05-23 05:00:00,4705,0.0,0.0,0.0,05:00:00,False,R
766318,RIT-ROOSEVELT,R,5554,299,2017-05-23 08:18:52,4705,0.0,0.0,0.0,08:18:52,False,R
766319,RIT-ROOSEVELT,R,5554,299,2017-05-23 09:00:00,4705,0.0,0.0,0.0,09:00:00,False,R
766320,RIT-ROOSEVELT,R,5554,299,2017-05-23 13:00:00,4705,0.0,0.0,0.0,13:00:00,False,R
766321,RIT-ROOSEVELT,R,5554,299,2017-05-23 17:00:00,4705,0.0,0.0,0.0,17:00:00,False,R
766322,RIT-ROOSEVELT,R,5554,299,2017-05-23 21:00:00,4705,0.0,0.0,0.0,21:00:00,False,R
766323,RIT-ROOSEVELT,R,5554,299,2017-05-24 01:00:00,4705,0.0,0.0,0.0,01:00:00,False,R
766324,RIT-ROOSEVELT,R,5554,299,2017-05-24 05:00:00,4705,0.0,0.0,0.0,05:00:00,False,R
766325,RIT-ROOSEVELT,R,5554,299,2017-05-24 09:00:00,4705,0.0,0.0,0.0,09:00:00,False,R
766326,RIT-ROOSEVELT,R,5554,299,2017-05-24 13:00:00,4705,0.0,0.0,0.0,13:00:00,False,R
766327,RIT-ROOSEVELT,R,5554,299,2017-05-24 17:00:00,4705,0.0,0.0,0.0,17:00:00,False,R
766328,RIT-ROOSEVELT,R,5554,299,2017-05-24 21:00:00,4705,0.0,0.0,0.0,21:00:00,False,R
766329,RIT-ROOSEVELT,R,5554,299,2017-05-25 01:00:00,4705,0.0,0.0,0.0,01:00:00,False,R
766330,RIT-ROOSEVELT,R,5554,299,2017-05-25 05:00:00,4705,0.0,0.0,0.0,05:00:00,False,R
766331,RIT-ROOSEVELT,R,5554,299,2017-05-25 09:00:00,4705,0.0,0.0,0.0,09:00:00,False,R
766332,RIT-ROOSEVELT,R,5554,299,2017-05-25 13:00:00,4705,0.0,0.0,0.0,13:00:00,False,R
766333,RIT-ROOSEVELT,R,5554,299,2017-05-25 17:00:00,4705,0.0,0.0,0.0,17:00:00,False,R
766334,RIT-ROOSEVELT,R,5554,299,2017-05-25 21:00:00,4705,0.0,0.0,0.0,21:00:00,False,R
766335,RIT-ROOSEVELT,R,5554,299,2017-05-26 01:00:00,4705,0.0,0.0,0.0,01:00:00,False,R
766336,RIT-ROOSEVELT,R,5554,299,2017-05-26 05:00:00,4705,0.0,0.0,0.0,05:00:00,False,R
766337,RIT-ROOSEVELT,R,5554,299,2017-05-26 09:00:00,4705,0.0,0.0,0.0,09:00:00,False,R
766338,RIT-ROOSEVELT,R,5554,299,2017-05-26 13:00:00,4705,0.0,0.0,0.0,13:00:00,False,R
766339,RIT-ROOSEVELT,R,5554,299,2017-05-26 17:00:00,4705,0.0,0.0,0.0,17:00:00,False,R
766340,RIT-ROOSEVELT,R,5554,299,2017-05-26 21:00:00,4705,0.0,0.0,0.0,21:00:00,False,R

In [100]:
# keeps only differences between same stations and eliminates first record for each station since we have nothing to compare it to
df = df[df.station_diff == 0.0]
df

,STATION,LINENAME,ENTRIES,EXITS,parsed_datetime,station_id,entry_num,exit_num,station_diff,time,Weekend,line_sort
1,59 ST,NQR456W,6157810,2085353,2017-04-29 08:00:00,0,33.0,34.0,0.0,08:00:00,True,456NQRW
2,59 ST,NQR456W,6157963,2085453,2017-04-29 12:00:00,0,153.0,100.0,0.0,12:00:00,True,456NQRW
3,59 ST,NQR456W,6158212,2085529,2017-04-29 16:00:00,0,249.0,76.0,0.0,16:00:00,True,456NQRW
4,59 ST,NQR456W,6158521,2085589,2017-04-29 20:00:00,0,309.0,60.0,0.0,20:00:00,True,456NQRW
5,59 ST,NQR456W,6158637,2085612,2017-04-30 00:00:00,0,116.0,23.0,0.0,00:00:00,True,456NQRW
6,59 ST,NQR456W,6158654,2085617,2017-04-30 04:00:00,0,17.0,5.0,0.0,04:00:00,True,456NQRW
7,59 ST,NQR456W,6158661,2085641,2017-04-30 08:00:00,0,7.0,24.0,0.0,08:00:00,True,456NQRW
8,59 ST,NQR456W,6158703,2085730,2017-04-30 12:00:00,0,42.0,89.0,0.0,12:00:00,True,456NQRW
9,59 ST,NQR456W,6158797,2085785,2017-04-30 16:00:00,0,94.0,55.0,0.0,16:00:00,True,456NQRW
10,59 ST,NQR456W,6159015,2085824,2017-04-30 20:00:00,0,218.0,39.0,0.0,20:00:00,True,456NQRW
11,59 ST,NQR456W,6159107,2085842,2017-05-01 00:00:00,0,92.0,18.0,0.0,00:00:00,False,456NQRW
12,59 ST,NQR456W,6159116,2085849,2017-05-01 04:00:00,0,9.0,7.0,0.0,04:00:00,False,456NQRW
13,59 ST,NQR456W,6159166,2085976,2017-05-01 08:00:00,0,50.0,127.0,0.0,08:00:00,False,456NQRW
14,59 ST,NQR456W,6159331,2086218,2017-05-01 12:00:00,0,165.0,242.0,0.0,12:00:00,False,456NQRW
15,59 ST,NQR456W,6159595,2086299,2017-05-01 16:00:00,0,264.0,81.0,0.0,16:00:00,False,456NQRW
16,59 ST,NQR456W,6160374,2086358,2017-05-01 20:00:00,0,779.0,59.0,0.0,20:00:00,False,456NQRW
17,59 ST,NQR456W,6160508,2086374,2017-05-02 00:00:00,0,134.0,16.0,0.0,00:00:00,False,456NQRW
18,59 ST,NQR456W,6160514,2086379,2017-05-02 04:00:00,0,6.0,5.0,0.0,04:00:00,False,456NQRW
19,59 ST,NQR456W,6160555,2086499,2017-05-02 08:00:00,0,41.0,120.0,0.0,08:00:00,False,456NQRW
20,59 ST,NQR456W,6160711,2086769,2017-05-02 12:00:00,0,156.0,270.0,0.0,12:00:00,False,456NQRW
21,59 ST,NQR456W,6161012,2086835,2017-05-02 16:00:00,0,301.0,66.0,0.0,16:00:00,False,456NQRW
22,59 ST,NQR456W,6161830,2086908,2017-05-02 20:00:00,0,818.0,73.0,0.0,20:00:00,False,456NQRW
23,59 ST,NQR456W,6162061,2086933,2017-05-03 00:00:00,0,231.0,25.0,0.0,00:00:00,False,456NQRW
24,59 ST,NQR456W,6162082,2086939,2017-05-03 04:00:00,0,21.0,6.0,0.0,04:00:00,False,456NQRW
25,59 ST,NQR456W,6162129,2087070,2017-05-03 08:00:00,0,47.0,131.0,0.0,08:00:00,False,456NQRW
26,59 ST,NQR456W,6162287,2087324,2017-05-03 12:00:00,0,158.0,254.0,0.0,12:00:00,False,456NQRW
27,59 ST,NQR456W,6162575,2087391,2017-05-03 16:00:00,0,288.0,67.0,0.0,16:00:00,False,456NQRW
28,59 ST,NQR456W,6163254,2087451,2017-05-03 20:00:00,0,679.0,60.0,0.0,20:00:00,False,456NQRW
29,59 ST,NQR456W,6163517,2087485,2017-05-04 00:00:00,0,263.0,34.0,0.0,00:00:00,False,456NQRW
30,59 ST,NQR456W,6163534,2087487,2017-05-04 04:00:00,0,17.0,2.0,0.0,04:00:00,False,456NQRW
...,...,...,...,...,...,...,...,...,...,...,...,...
766311,RIT-ROOSEVELT,R,5554,299,2017-05-22 05:00:00,4705,0.0,0.0,0.0,05:00:00,False,R
766312,RIT-ROOSEVELT,R,5554,299,2017-05-22 09:00:00,4705,0.0,0.0,0.0,09:00:00,False,R
766313,RIT-ROOSEVELT,R,5554,299,2017-05-22 13:00:00,4705,0.0,0.0,0.0,13:00:00,False,R
766314,RIT-ROOSEVELT,R,5554,299,2017-05-22 17:00:00,4705,0.0,0.0,0.0,17:00:00,False,R
766315,RIT-ROOSEVELT,R,5554,299,2017-05-22 21:00:00,4705,0.0,0.0,0.0,21:00:00,False,R
766316,RIT-ROOSEVELT,R,5554,299,2017-05-23 01:00:00,4705,0.0,0.0,0.0,01:00:00,False,R
766317,RIT-ROOSEVELT,R,5554,299,2017-05-23 05:00:00,4705,0.0,0.0,0.0,05:00:00,False,R
766318,RIT-ROOSEVELT,R,5554,299,2017-05-23 08:18:52,4705,0.0,0.0,0.0,08:18:52,False,R
766319,RIT-ROOSEVELT,R,5554,299,2017-05-23 09:00:00,4705,0.0,0.0,0.0,09:00:00,False,R
766320,RIT-ROOSEVELT,R,5554,299,2017-05-23 13:00:00,4705,0.0,0.0,0.0,13:00:00,False,R
766321,RIT-ROOSEVELT,R,5554,299,2017-05-23 17:00:00,4705,0.0,0.0,0.0,17:00:00,False,R
766322,RIT-ROOSEVELT,R,5554,299,2017-05-23 21:00:00,4705,0.0,0.0,0.0,21:00:00,False,R
766323,RIT-ROOSEVELT,R,5554,299,2017-05-24 01:00:00,4705,0.0,0.0,0.0,01:00:00,False,R
766324,RIT-ROOSEVELT,R,5554,299,2017-05-24 05:00:00,4705,0.0,0.0,0.0,05:00:00,False,R
766325,RIT-ROOSEVELT,R,5554,299,2017-05-24 09:00:00,4705,0.0,0.0,0.0,09:00:00,False,R
766326,RIT-ROOSEVELT,R,5554,299,2017-05-24 13:00:00,4705,0.0,0.0,0.0,13:00:00,False,R
766327,RIT-ROOSEVELT,R,5554,299,2017-05-24 17:00:00,4705,0.0,0.0,0.0,17:00:00,False,R
766328,RIT-ROOSEVELT,R,5554,299,2017-05-24 21:00:00,4705,0.0,0.0,0.0,21:00:00,False,R
766329,RIT-ROOSEVELT,R,5554,299,2017-05-25 01:00:00,4705,0.0,0.0,0.0,01:00:00,False,R
766330,RIT-ROOSEVELT,R,5554,299,2017-05-25 05:00:00,4705,0.0,0.0,0.0,05:00:00,False,R
766331,RIT-ROOSEVELT,R,5554,299,2017-05-25 09:00:00,4705,0.0,0.0,0.0,09:00:00,False,R
766332,RIT-ROOSEVELT,R,5554,299,2017-05-25 13:00:00,4705,0.0,0.0,0.0,13:00:00,False,R
766333,RIT-ROOSEVELT,R,5554,299,2017-05-25 17:00:00,4705,0.0,0.0,0.0,17:00:00,False,R
766334,RIT-ROOSEVELT,R,5554,299,2017-05-25 21:00:00,4705,0.0,0.0,0.0,21:00:00,False,R
766335,RIT-ROOSEVELT,R,5554,299,2017-05-26 01:00:00,4705,0.0,0.0,0.0,01:00:00,False,R
766336,RIT-ROOSEVELT,R,5554,299,2017-05-26 05:00:00,4705,0.0,0.0,0.0,05:00:00,False,R
766337,RIT-ROOSEVELT,R,5554,299,2017-05-26 09:00:00,4705,0.0,0.0,0.0,09:00:00,False,R
766338,RIT-ROOSEVELT,R,5554,299,2017-05-26 13:00:00,4705,0.0,0.0,0.0,13:00:00,False,R
766339,RIT-ROOSEVELT,R,5554,299,2017-05-26 17:00:00,4705,0.0,0.0,0.0,17:00:00,False,R
766340,RIT-ROOSEVELT,R,5554,299,2017-05-26 21:00:00,4705,0.0,0.0,0.0,21:00:00,False,R

In [17]:
df.loc[30:50]

,STATION,LINENAME,ENTRIES,EXITS,parsed_datetime,station_id,entry_num,exit_num,station_diff
30,59 ST,NQR456W,6163517,2087485,2017-05-04 00:00:00,0,263.0,34.0,0.0
31,59 ST,NQR456W,6163534,2087487,2017-05-04 04:00:00,0,17.0,2.0,0.0
32,59 ST,NQR456W,6163576,2087581,2017-05-04 08:00:00,0,42.0,94.0,0.0
33,59 ST,NQR456W,6163739,2087856,2017-05-04 12:00:00,0,163.0,275.0,0.0
34,59 ST,NQR456W,6164051,2087916,2017-05-04 16:00:00,0,312.0,60.0,0.0
35,59 ST,NQR456W,6164865,2087987,2017-05-04 20:00:00,0,814.0,71.0,0.0
36,59 ST,NQR456W,6165120,2088020,2017-05-05 00:00:00,0,255.0,33.0,0.0
37,59 ST,NQR456W,6165147,2088024,2017-05-05 04:00:00,0,27.0,4.0,0.0
38,59 ST,NQR456W,6165183,2088112,2017-05-05 08:00:00,0,36.0,88.0,0.0
39,59 ST,NQR456W,6165346,2088396,2017-05-05 12:00:00,0,163.0,284.0,0.0
40,59 ST,NQR456W,6165481,2088433,2017-05-05 16:00:00,0,135.0,37.0,0.0
41,59 ST,NQR456W,6166192,2088501,2017-05-05 20:00:00,0,711.0,68.0,0.0
43,59 ST,NQR456W,5580437,1235901,2017-04-29 04:00:00,1,21.0,2.0,0.0
44,59 ST,NQR456W,5580462,1235919,2017-04-29 08:00:00,1,25.0,18.0,0.0
45,59 ST,NQR456W,5580581,1235986,2017-04-29 12:00:00,1,119.0,67.0,0.0
46,59 ST,NQR456W,5580766,1236039,2017-04-29 16:00:00,1,185.0,53.0,0.0
47,59 ST,NQR456W,5581062,1236080,2017-04-29 20:00:00,1,296.0,41.0,0.0
48,59 ST,NQR456W,5581232,1236100,2017-04-30 00:00:00,1,170.0,20.0,0.0
49,59 ST,NQR456W,5581273,1236103,2017-04-30 04:00:00,1,41.0,3.0,0.0
50,59 ST,NQR456W,5581282,1236117,2017-04-30 08:00:00,1,9.0,14.0,0.0

In [18]:
df['time'] = df.apply(lambda row: row.parsed_datetime.time(), axis=1)

/Users/matiasbeeck/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [19]:
# df['weekday'] = df['parsed_datetime'].dt.weekday
# df['weekday_bin'] = df.apply(lambda row: 1 if df.weekday < 5 else 0, axis=1)

df['Weekday'] = df['parsed_datetime'].dt.weekday
df['Weekend'] = 0
df['Weekend'] = df['Weekday'] >= 5
df.drop('Weekday', axis=1, inplace = True)
df

/Users/matiasbeeck/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/Users/matiasbeeck/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
/Users/matiasbeeck/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/matiasbeeck/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

,STATION,LINENAME,ENTRIES,EXITS,parsed_datetime,station_id,entry_num,exit_num,station_diff,time,Weekend
1,59 ST,NQR456W,6157777,2085319,2017-04-29 04:00:00,0,37.0,4.0,0.0,04:00:00,True
2,59 ST,NQR456W,6157810,2085353,2017-04-29 08:00:00,0,33.0,34.0,0.0,08:00:00,True
3,59 ST,NQR456W,6157963,2085453,2017-04-29 12:00:00,0,153.0,100.0,0.0,12:00:00,True
4,59 ST,NQR456W,6158212,2085529,2017-04-29 16:00:00,0,249.0,76.0,0.0,16:00:00,True
5,59 ST,NQR456W,6158521,2085589,2017-04-29 20:00:00,0,309.0,60.0,0.0,20:00:00,True
6,59 ST,NQR456W,6158637,2085612,2017-04-30 00:00:00,0,116.0,23.0,0.0,00:00:00,True
7,59 ST,NQR456W,6158654,2085617,2017-04-30 04:00:00,0,17.0,5.0,0.0,04:00:00,True
8,59 ST,NQR456W,6158661,2085641,2017-04-30 08:00:00,0,7.0,24.0,0.0,08:00:00,True
9,59 ST,NQR456W,6158703,2085730,2017-04-30 12:00:00,0,42.0,89.0,0.0,12:00:00,True
10,59 ST,NQR456W,6158797,2085785,2017-04-30 16:00:00,0,94.0,55.0,0.0,16:00:00,True
11,59 ST,NQR456W,6159015,2085824,2017-04-30 20:00:00,0,218.0,39.0,0.0,20:00:00,True
12,59 ST,NQR456W,6159107,2085842,2017-05-01 00:00:00,0,92.0,18.0,0.0,00:00:00,False
13,59 ST,NQR456W,6159116,2085849,2017-05-01 04:00:00,0,9.0,7.0,0.0,04:00:00,False
14,59 ST,NQR456W,6159166,2085976,2017-05-01 08:00:00,0,50.0,127.0,0.0,08:00:00,False
15,59 ST,NQR456W,6159331,2086218,2017-05-01 12:00:00,0,165.0,242.0,0.0,12:00:00,False
16,59 ST,NQR456W,6159595,2086299,2017-05-01 16:00:00,0,264.0,81.0,0.0,16:00:00,False
17,59 ST,NQR456W,6160374,2086358,2017-05-01 20:00:00,0,779.0,59.0,0.0,20:00:00,False
18,59 ST,NQR456W,6160508,2086374,2017-05-02 00:00:00,0,134.0,16.0,0.0,00:00:00,False
19,59 ST,NQR456W,6160514,2086379,2017-05-02 04:00:00,0,6.0,5.0,0.0,04:00:00,False
20,59 ST,NQR456W,6160555,2086499,2017-05-02 08:00:00,0,41.0,120.0,0.0,08:00:00,False
21,59 ST,NQR456W,6160711,2086769,2017-05-02 12:00:00,0,156.0,270.0,0.0,12:00:00,False
22,59 ST,NQR456W,6161012,2086835,2017-05-02 16:00:00,0,301.0,66.0,0.0,16:00:00,False
23,59 ST,NQR456W,6161830,2086908,2017-05-02 20:00:00,0,818.0,73.0,0.0,20:00:00,False
24,59 ST,NQR456W,6162061,2086933,2017-05-03 00:00:00,0,231.0,25.0,0.0,00:00:00,False
25,59 ST,NQR456W,6162082,2086939,2017-05-03 04:00:00,0,21.0,6.0,0.0,04:00:00,False
26,59 ST,NQR456W,6162129,2087070,2017-05-03 08:00:00,0,47.0,131.0,0.0,08:00:00,False
27,59 ST,NQR456W,6162287,2087324,2017-05-03 12:00:00,0,158.0,254.0,0.0,12:00:00,False
28,59 ST,NQR456W,6162575,2087391,2017-05-03 16:00:00,0,288.0,67.0,0.0,16:00:00,False
29,59 ST,NQR456W,6163254,2087451,2017-05-03 20:00:00,0,679.0,60.0,0.0,20:00:00,False
30,59 ST,NQR456W,6163517,2087485,2017-05-04 00:00:00,0,263.0,34.0,0.0,00:00:00,False
...,...,...,...,...,...,...,...,...,...,...,...
785059,RIT-ROOSEVELT,R,5554,299,2017-05-22 05:00:00,4705,0.0,0.0,0.0,05:00:00,False
785060,RIT-ROOSEVELT,R,5554,299,2017-05-22 09:00:00,4705,0.0,0.0,0.0,09:00:00,False
785061,RIT-ROOSEVELT,R,5554,299,2017-05-22 13:00:00,4705,0.0,0.0,0.0,13:00:00,False
785062,RIT-ROOSEVELT,R,5554,299,2017-05-22 17:00:00,4705,0.0,0.0,0.0,17:00:00,False
785063,RIT-ROOSEVELT,R,5554,299,2017-05-22 21:00:00,4705,0.0,0.0,0.0,21:00:00,False
785064,RIT-ROOSEVELT,R,5554,299,2017-05-23 01:00:00,4705,0.0,0.0,0.0,01:00:00,False
785065,RIT-ROOSEVELT,R,5554,299,2017-05-23 05:00:00,4705,0.0,0.0,0.0,05:00:00,False
785066,RIT-ROOSEVELT,R,5554,299,2017-05-23 08:18:52,4705,0.0,0.0,0.0,08:18:52,False
785067,RIT-ROOSEVELT,R,5554,299,2017-05-23 09:00:00,4705,0.0,0.0,0.0,09:00:00,False
785068,RIT-ROOSEVELT,R,5554,299,2017-05-23 13:00:00,4705,0.0,0.0,0.0,13:00:00,False
785069,RIT-ROOSEVELT,R,5554,299,2017-05-23 17:00:00,4705,0.0,0.0,0.0,17:00:00,False
785070,RIT-ROOSEVELT,R,5554,299,2017-05-23 21:00:00,4705,0.0,0.0,0.0,21:00:00,False
785071,RIT-ROOSEVELT,R,5554,299,2017-05-24 01:00:00,4705,0.0,0.0,0.0,01:00:00,False
785072,RIT-ROOSEVELT,R,5554,299,2017-05-24 05:00:00,4705,0.0,0.0,0.0,05:00:00,False
785073,RIT-ROOSEVELT,R,5554,299,2017-05-24 09:00:00,4705,0.0,0.0,0.0,09:00:00,False
785074,RIT-ROOSEVELT,R,5554,299,2017-05-24 13:00:00,4705,0.0,0.0,0.0,13:00:00,False
785075,RIT-ROOSEVELT,R,5554,299,2017-05-24 17:00:00,4705,0.0,0.0,0.0,17:00:00,False
785076,RIT-ROOSEVELT,R,5554,299,2017-05-24 21:00:00,4705,0.0,0.0,0.0,21:00:00,False
785077,RIT-ROOSEVELT,R,5554,299,2017-05-25 01:00:00,4705,0.0,0.0,0.0,01:00:00,False
785078,RIT-ROOSEVELT,R,5554,299,2017-05-25 05:00:00,4705,0.0,0.0,0.0,05:00:00,False
785079,RIT-ROOSEVELT,R,5554,299,2017-05-25 09:00:00,4705,0.0,0.0,0.0,09:00:00,False
785080,RIT-ROOSEVELT,R,5554,299,2017-05-25 13:00:00,4705,0.0,0.0,0.0,13:00:00,False
785081,RIT-ROOSEVELT,R,5554,299,2017-05-25 17:00:00,4705,0.0,0.0,0.0,17:00:00,False
785082,RIT-ROOSEVELT,R,5554,299,2017-05-25 21:00:00,4705,0.0,0.0,0.0,21:00:00,False
785083,RIT-ROOSEVELT,R,5554,299,2017-05-26 01:00:00,4705,0.0,0.0,0.0,01:00:00,False
785084,RIT-ROOSEVELT,R,5554,299,2017-05-26 05:00:00,4705,0.0,0.0,0.0,05:00:00,False
785085,RIT-ROOSEVELT,R,5554,299,2017-05-26 09:00:00,4705,0.0,0.0,0.0,09:00:00,False
785086,RIT-ROOSEVELT,R,5554,299,2017-05-26 13:00:00,4705,0.0,0.0,0.0,13:00:00,False
785087,RIT-ROOSEVELT,R,5554,299,2017-05-26 17:00:00,4705,0.0,0.0,0.0,17:00:00,False
785088,RIT-ROOSEVELT,R,5554,299,2017-05-26 21:00:00,4705,0.0,0.0,0.0,21:00:00,False

In [35]:
df['line_sort'] = df.apply(lambda row: ''.join(sorted(row.LINENAME)), axis=1)

/Users/matiasbeeck/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

                              LINENAME
STATION         LINENAME
1 AV            L                 1639
103 ST          1                  984
                6                  999
                BC                 492
103 ST-CORONA   7                 1502
104 ST          A                  820
                JZ                 588
110 ST          6                  993
111 ST          7                  820
                A                 1147
                J                  663
116 ST          23                1320
                6                 1319
                BC                 999
116 ST-COLUMBIA 1                  984
121 ST          JZ                 652
125 ST          1                  835
                23                1321
                456               2290
                ACBD              2632
135 ST          23                2005
                BC                1798
137 ST CITY COL 1                 1645
138/GRAND CONC  45                 492
14 ST           123FLM            2455
                ACEL              1636
                FLM123            2931
14 ST-UNION SQ  456LNQRW          1951
                LNQR456W          4273
145 ST          1                 1148
...                                ...
TIMES SQ-42 ST  1237ACENQRS       1476
                1237ACENQRSW      5418
                ACENQRS1237W      1319
TOMPKINSVILLE   1                 1162
TREMONT AV      BD                1476
TWENTY THIRD ST 1                 1389
UNION ST        R                  999
UTICA AV        AC                2132
V.CORTLANDT PK  1                  656
VAN SICLEN AV   3                  667
                JZ                 492
VAN SICLEN AVE  C                  492
VERNON-JACKSON  7                 2126
W 4 ST-WASH SQ  ABCDEFM           3139
W 8 ST-AQUARIUM FQ                1311
WAKEFIELD/241   2                  820
WALL ST         23                3634
                45                4572
WEST FARMS SQ   25                1467
WESTCHESTER SQ  6                  498
WHITEHALL S-FRY R1W               2474
WHITLOCK AV     6                  983
WILSON AV       L                  735
WINTHROP ST     25                 660
WOODHAVEN BLVD  JZ                1320
                MR                1838
WOODLAWN        4                  820
WORLD TRADE CTR ACE23             1761
YORK ST         F                  482
ZEREGA AV       6                  984

[475 rows x 1 columns]

In [36]:
officialdf = df

In [41]:
df.groupby(['STATION','line_sort'])[['line_sort']].count()

                              line_sort
STATION         line_sort
1 AV            L                  1639
103 ST          1                   984
                6                   999
                BC                  492
103 ST-CORONA   7                  1502
104 ST          A                   820
                JZ                  588
110 ST          6                   993
111 ST          7                   820
                A                  1147
                J                   663
116 ST          23                 1320
                6                  1319
                BC                  999
116 ST-COLUMBIA 1                   984
121 ST          JZ                  652
125 ST          1                   835
                23                 1321
                456                2290
                ABCD               2632
135 ST          23                 2005
                BC                 1798
137 ST CITY COL 1                  1645
138/GRAND CONC  45                  492
14 ST           123FLM             5386
                ACEL               1636
14 ST-UNION SQ  456LNQRW           6224
145 ST          1                  1148
                3                   495
                ABCD               1488
...                                 ...
THIRTY THIRD ST 1                  2797
TIMES SQ-42 ST  1237ACENQRS        1476
                1237ACENQRSW       6737
TOMPKINSVILLE   1                  1162
TREMONT AV      BD                 1476
TWENTY THIRD ST 1                  1389
UNION ST        R                   999
UTICA AV        AC                 2132
V.CORTLANDT PK  1                   656
VAN SICLEN AV   3                   667
                JZ                  492
VAN SICLEN AVE  C                   492
VERNON-JACKSON  7                  2126
W 4 ST-WASH SQ  ABCDEFM            3139
W 8 ST-AQUARIUM FQ                 1311
WAKEFIELD/241   2                   820
WALL ST         23                 3634
                45                 4572
WEST FARMS SQ   25                 1467
WESTCHESTER SQ  6                   498
WHITEHALL S-FRY 1RW                2474
WHITLOCK AV     6                   983
WILSON AV       L                   735
WINTHROP ST     25                  660
WOODHAVEN BLVD  JZ                 1320
                MR                 1838
WOODLAWN        4                   820
WORLD TRADE CTR 23ACE              1761
YORK ST         F                   482
ZEREGA AV       6                   984

[465 rows x 1 columns]

In [101]:
df.groupby(['STATION','line_sort'])[['entry_num']].sum().sort_values(by=['entry_num'])

                                 entry_num
STATION         line_sort
BAY RIDGE AV    R             1.000000e+00
ORCHARD BEACH   6             7.700000e+01
BEACH 105 ST    AS            6.353000e+03
BROAD CHANNEL   AS            7.017000e+03
BEACH 98 ST     AS            1.257100e+04
ROCKAWAY PARK B AS            1.629500e+04
BEACH 44 ST     A             1.807700e+04
121 ST          JZ            2.076600e+04
TOMPKINSVILLE   1             2.093300e+04
BEACH 90 ST     AS            2.155500e+04
AQUEDUCT N.COND A             2.375000e+04
E 143/ST MARY'S 6             2.437300e+04
BEACH 36 ST     A             2.474300e+04
BAY PKWY        F             2.858300e+04
86 ST           N             2.989600e+04
20 AV           N             3.055100e+04
104 ST          JZ            3.133600e+04
CYPRESS HILLS   J             3.479700e+04
AVENUE U        N             3.648800e+04
KINGS HWY       N             3.752400e+04
AQUEDUCT RACETR A             4.026500e+04
AVENUE I        F             4.057200e+04
NEPTUNE AV      F             4.162800e+04
21 ST           G             4.259900e+04
104 ST          A             4.280900e+04
BOTANIC GARDEN  2345S         4.315200e+04
FT HAMILTON PKY N             4.476300e+04
ATLANTIC AV     L             4.592100e+04
PARK PLACE      S             4.691600e+04
55 ST           D             4.873800e+04
...                                    ...
59 ST COLUMBUS  1ABCD         1.840205e+06
TIMES SQ-42 ST  1237ACENQRSW  1.958228e+06
FULTON ST       2345ACJZ      2.083040e+06
NORTHERN BLVD   MR            2.120462e+06
34 ST-PENN STA  ACE           2.195858e+06
JOURNAL SQUARE  1             2.254907e+06
3 AV-149 ST     25            2.736230e+06
CHAMBERS ST     456JZ         2.862899e+06
PATH NEW WTC    1             2.954339e+06
34 ST-HERALD SQ BDFMNQRW      3.081982e+06
14 ST-UNION SQ  456LNQRW      4.496547e+06
CHURCH AV       BQ            5.052028e+06
42 ST-PORT AUTH 1237ACENQRSW  7.635386e+06
20 AV           D             7.708032e+06
CRESCENT ST     JZ            8.030706e+06
SUTTER AV       L             1.193901e+07
47-50 STS ROCK  BDFM          1.478669e+07
86 ST           1             1.695616e+07
96 ST           6             1.984803e+07
BEDFORD PK BLVD BD            3.069226e+07
BURNSIDE AV     4             3.110885e+07
AVENUE M        BQ            3.368447e+07
111 ST          A             8.361891e+07
BOROUGH HALL    2345R         9.912184e+07
RECTOR ST       NRW           1.010191e+08
66 ST-LINCOLN   1             1.175406e+08
96 ST           123           6.093110e+08
72 ST           123           6.841861e+08
GRD CNTRL-42 ST 4567S         1.368785e+09
EASTCHSTER/DYRE 5             1.557797e+09

[465 rows x 1 columns]

In [102]:
df[df.STATION == 'EASTCHSTER/DYRE'].sort_values(by='entry_num')
# df.loc[df.entry_num < 0, :]['STATION'].unique()

,STATION,LINENAME,ENTRIES,EXITS,parsed_datetime,station_id,entry_num,exit_num,station_diff,time,Weekend,line_sort
190631,EASTCHSTER/DYRE,5,1334708,2553279,2017-04-29 09:00:00,4658,0.000000e+00,0.000000e+00,0.0,09:00:00,True,5
573646,EASTCHSTER/DYRE,5,5938157,7596902,2017-05-14 13:00:00,4659,0.000000e+00,0.000000e+00,0.0,13:00:00,True,5
573645,EASTCHSTER/DYRE,5,5938157,7596902,2017-05-14 09:00:00,4659,0.000000e+00,0.000000e+00,0.0,09:00:00,True,5
573644,EASTCHSTER/DYRE,5,5938157,7596902,2017-05-14 05:00:00,4659,0.000000e+00,0.000000e+00,0.0,05:00:00,True,5
573643,EASTCHSTER/DYRE,5,5938157,7596902,2017-05-14 01:00:00,4659,0.000000e+00,0.000000e+00,0.0,01:00:00,True,5
573641,EASTCHSTER/DYRE,5,5938156,7596902,2017-05-13 17:00:00,4659,0.000000e+00,0.000000e+00,0.0,17:00:00,True,5
573640,EASTCHSTER/DYRE,5,5938156,7596902,2017-05-13 13:00:00,4659,0.000000e+00,0.000000e+00,0.0,13:00:00,True,5
573609,EASTCHSTER/DYRE,5,1339180,2561501,2017-05-15 05:00:00,4658,0.000000e+00,0.000000e+00,0.0,05:00:00,False,5
573608,EASTCHSTER/DYRE,5,1339180,2561501,2017-05-15 01:00:00,4658,0.000000e+00,0.000000e+00,0.0,01:00:00,False,5
573607,EASTCHSTER/DYRE,5,1339180,2561501,2017-05-14 21:00:00,4658,0.000000e+00,0.000000e+00,0.0,21:00:00,True,5
573606,EASTCHSTER/DYRE,5,1339180,2561501,2017-05-14 17:00:00,4658,0.000000e+00,0.000000e+00,0.0,17:00:00,True,5
573605,EASTCHSTER/DYRE,5,1339180,2561501,2017-05-14 13:00:00,4658,0.000000e+00,0.000000e+00,0.0,13:00:00,True,5
573647,EASTCHSTER/DYRE,5,5938157,7596902,2017-05-14 17:00:00,4659,0.000000e+00,0.000000e+00,0.0,17:00:00,True,5
573604,EASTCHSTER/DYRE,5,1339180,2561501,2017-05-14 09:00:00,4658,0.000000e+00,0.000000e+00,0.0,09:00:00,True,5
190795,EASTCHSTER/DYRE,5,2523023,1046466,2017-04-29 09:00:00,4662,0.000000e+00,0.000000e+00,0.0,09:00:00,True,5
573602,EASTCHSTER/DYRE,5,1339180,2561501,2017-05-14 01:00:00,4658,0.000000e+00,0.000000e+00,0.0,01:00:00,True,5
190797,EASTCHSTER/DYRE,5,2523024,1046466,2017-04-29 17:00:00,4662,0.000000e+00,0.000000e+00,0.0,17:00:00,True,5
190798,EASTCHSTER/DYRE,5,2523024,1046466,2017-04-29 21:00:00,4662,0.000000e+00,0.000000e+00,0.0,21:00:00,True,5
190799,EASTCHSTER/DYRE,5,2523024,1046466,2017-04-30 01:00:00,4662,0.000000e+00,0.000000e+00,0.0,01:00:00,True,5
190800,EASTCHSTER/DYRE,5,2523024,1046466,2017-04-30 05:00:00,4662,0.000000e+00,0.000000e+00,0.0,05:00:00,True,5
190801,EASTCHSTER/DYRE,5,2523024,1046466,2017-04-30 09:00:00,4662,0.000000e+00,0.000000e+00,0.0,09:00:00,True,5
190802,EASTCHSTER/DYRE,5,2523024,1046466,2017-04-30 13:00:00,4662,0.000000e+00,0.000000e+00,0.0,13:00:00,True,5
190803,EASTCHSTER/DYRE,5,2523024,1046466,2017-04-30 17:00:00,4662,0.000000e+00,0.000000e+00,0.0,17:00:00,True,5
190804,EASTCHSTER/DYRE,5,2523024,1046466,2017-04-30 21:00:00,4662,0.000000e+00,0.000000e+00,0.0,21:00:00,True,5
190805,EASTCHSTER/DYRE,5,2523024,1046466,2017-05-01 01:00:00,4662,0.000000e+00,0.000000e+00,0.0,01:00:00,False,5
573603,EASTCHSTER/DYRE,5,1339180,2561501,2017-05-14 05:00:00,4658,0.000000e+00,0.000000e+00,0.0,05:00:00,True,5
573648,EASTCHSTER/DYRE,5,5938157,7596902,2017-05-14 21:00:00,4659,0.000000e+00,0.000000e+00,0.0,21:00:00,True,5
573649,EASTCHSTER/DYRE,5,5938157,7596902,2017-05-15 01:00:00,4659,0.000000e+00,0.000000e+00,0.0,01:00:00,False,5
573650,EASTCHSTER/DYRE,5,5938157,7596902,2017-05-15 05:00:00,4659,0.000000e+00,0.000000e+00,0.0,05:00:00,False,5
573722,EASTCHSTER/DYRE,5,538949573,538463564,2017-05-13 13:00:00,4661,0.000000e+00,0.000000e+00,0.0,13:00:00,True,5
...,...,...,...,...,...,...,...,...,...,...,...,...
764506,EASTCHSTER/DYRE,5,538959966,538469732,2017-05-24 09:00:00,4661,7.280000e+02,1.220000e+02,0.0,09:00:00,False,5
573751,EASTCHSTER/DYRE,5,538954484,538466384,2017-05-18 09:00:00,4661,7.350000e+02,1.000000e+02,0.0,09:00:00,False,5
573692,EASTCHSTER/DYRE,5,2429934,2136453,2017-05-15 09:00:00,4660,7.390000e+02,1.740000e+02,0.0,09:00:00,False,5
190772,EASTCHSTER/DYRE,5,538937814,538455834,2017-05-02 09:00:00,4661,7.400000e+02,1.350000e+02,0.0,09:00:00,False,5
573745,EASTCHSTER/DYRE,5,538953085,538465501,2017-05-17 09:00:00,4661,7.420000e+02,1.570000e+02,0.0,09:00:00,False,5
190784,EASTCHSTER/DYRE,5,538940562,538457604,2017-05-04 09:00:00,4661,7.490000e+02,8.900000e+01,0.0,09:00:00,False,5
764465,EASTCHSTER/DYRE,5,2440896,2145733,2017-05-24 09:00:00,4660,7.500000e+02,2.080000e+02,0.0,09:00:00,False,5
573739,EASTCHSTER/DYRE,5,538951703,538464580,2017-05-16 09:00:00,4661,7.520000e+02,9.500000e+01,0.0,09:00:00,False,5
382896,EASTCHSTER/DYRE,5,538943462,538459394,2017-05-08 09:00:00,4661,7.550000e+02,1.140000e+02,0.0,09:00:00,False,5
190749,EASTCHSTER/DYRE,5,2420351,2128334,2017-05-05 09:00:00,4660,7.620000e+02,1.720000e+02,0.0,09:00:00,False,5
190725,EASTCHSTER/DYRE,5,2413897,2122813,2017-05-01 09:00:00,4660,7.620000e+02,1.820000e+02,0.0,09:00:00,False,5
764500,EASTCHSTER/DYRE,5,538958584,538468877,2017-05-23 09:00:00,4661,7.630000e+02,1.020000e+02,0.0,09:00:00,False,5
573733,EASTCHSTER/DYRE,5,538950337,538463669,2017-05-15 09:00:00,4661,7.640000e+02,1.050000e+02,0.0,09:00:00,False,5
382908,EASTCHSTER/DYRE,5,538946258,538461019,2017-05-10 09:00:00,4661,7.670000e+02,8.700000e+01,0.0,09:00:00,False,5
190790,EASTCHSTER/DYRE,5,538942062,538458506,2017-05-05 09:00:00,4661,7.790000e+02,7.500000e+01,0.0,09:00:00,False,5
382902,EASTCHSTER/DYRE,5,538944849,538460136,2017-05-09 09:00:00,4661,7.790000e+02,6.900000e+01,0.0,09:00:00,False,5
764459,EASTCHSTER/DYRE,5,2439334,2144374,2017-05-23 09:00:00,4660,7.800000e+02,1.790000e+02,0.0,09:00:00,False,5
190743,EASTCHSTER/DYRE,5,2418753,2126918,2017-05-04 09:00:00,4660,7.820000e+02,2.020000e+02,0.0,09:00:00,False,5
382855,EASTCHSTER/DYRE,5,2421949,2129825,2017-05-08 09:00:00,4660,7.870000e+02,1.760000e+02,0.0,09:00:00,False,5
382879,EASTCHSTER/DYRE,5,2428401,2135195,2017-05-12 09:00:00,4660,7.880000e+02,1.480000e+02,0.0,09:00:00,False,5
573710,EASTCHSTER/DYRE,5,2434811,2140476,2017-05-18 09:00:00,4660,7.900000e+02,1.590000e+02,0.0,09:00:00,False,5
190737,EASTCHSTER/DYRE,5,2417128,2125523,2017-05-03 09:00:00,4660,7.960000e+02,1.990000e+02,0.0,09:00:00,False,5
573704,EASTCHSTER/DYRE,5,2433176,2139100,2017-05-17 09:00:00,4660,7.980000e+02,1.350000e+02,0.0,09:00:00,False,5
382861,EASTCHSTER/DYRE,5,2423516,2131119,2017-05-09 09:00:00,4660,7.980000e+02,1.740000e+02,0.0,09:00:00,False,5
573698,EASTCHSTER/DYRE,5,2431533,2137803,2017-05-16 09:00:00,4660,8.000000e+02,2.150000e+02,0.0,09:00:00,False,5
382867,EASTCHSTER/DYRE,5,2425138,2132507,2017-05-10 09:00:00,4660,8.010000e+02,1.870000e+02,0.0,09:00:00,False,5
764477,EASTCHSTER/DYRE,5,2444093,2148447,2017-05-26 09:00:00,4660,8.100000e+02,2.210000e+02,0.0,09:00:00,False,5
382873,EASTCHSTER/DYRE,5,2426757,2133902,2017-05-11 09:00:00,4660,8.150000e+02,1.940000e+02,0.0,09:00:00,False,5
190731,EASTCHSTER/DYRE,5,2415496,2124131,2017-05-02 09:00:00,4660,8.190000e+02,1.950000e+02,0.0,09:00:00,False,5
190828,EASTCHSTER/DYRE,5,1560221425,1728055986,2017-05-05 13:00:00,4662,1.557696e+09,1.727009e+09,0.0,13:00:00,False,5

In [103]:
df = df.reset_index()
df = df.drop('index', 1)
df[df.STATION == 'EASTCHSTER/DYRE'].sort_values(by='entry_num')

,STATION,LINENAME,ENTRIES,EXITS,parsed_datetime,station_id,entry_num,exit_num,station_diff,time,Weekend,line_sort
185979,EASTCHSTER/DYRE,5,1334708,2553279,2017-04-29 09:00:00,4658,0.000000e+00,0.000000e+00,0.0,09:00:00,True,5
559615,EASTCHSTER/DYRE,5,5938157,7596902,2017-05-14 13:00:00,4659,0.000000e+00,0.000000e+00,0.0,13:00:00,True,5
559614,EASTCHSTER/DYRE,5,5938157,7596902,2017-05-14 09:00:00,4659,0.000000e+00,0.000000e+00,0.0,09:00:00,True,5
559613,EASTCHSTER/DYRE,5,5938157,7596902,2017-05-14 05:00:00,4659,0.000000e+00,0.000000e+00,0.0,05:00:00,True,5
559612,EASTCHSTER/DYRE,5,5938157,7596902,2017-05-14 01:00:00,4659,0.000000e+00,0.000000e+00,0.0,01:00:00,True,5
559610,EASTCHSTER/DYRE,5,5938156,7596902,2017-05-13 17:00:00,4659,0.000000e+00,0.000000e+00,0.0,17:00:00,True,5
559609,EASTCHSTER/DYRE,5,5938156,7596902,2017-05-13 13:00:00,4659,0.000000e+00,0.000000e+00,0.0,13:00:00,True,5
559579,EASTCHSTER/DYRE,5,1339180,2561501,2017-05-15 05:00:00,4658,0.000000e+00,0.000000e+00,0.0,05:00:00,False,5
559578,EASTCHSTER/DYRE,5,1339180,2561501,2017-05-15 01:00:00,4658,0.000000e+00,0.000000e+00,0.0,01:00:00,False,5
559577,EASTCHSTER/DYRE,5,1339180,2561501,2017-05-14 21:00:00,4658,0.000000e+00,0.000000e+00,0.0,21:00:00,True,5
559576,EASTCHSTER/DYRE,5,1339180,2561501,2017-05-14 17:00:00,4658,0.000000e+00,0.000000e+00,0.0,17:00:00,True,5
559575,EASTCHSTER/DYRE,5,1339180,2561501,2017-05-14 13:00:00,4658,0.000000e+00,0.000000e+00,0.0,13:00:00,True,5
559616,EASTCHSTER/DYRE,5,5938157,7596902,2017-05-14 17:00:00,4659,0.000000e+00,0.000000e+00,0.0,17:00:00,True,5
559574,EASTCHSTER/DYRE,5,1339180,2561501,2017-05-14 09:00:00,4658,0.000000e+00,0.000000e+00,0.0,09:00:00,True,5
186139,EASTCHSTER/DYRE,5,2523023,1046466,2017-04-29 09:00:00,4662,0.000000e+00,0.000000e+00,0.0,09:00:00,True,5
559572,EASTCHSTER/DYRE,5,1339180,2561501,2017-05-14 01:00:00,4658,0.000000e+00,0.000000e+00,0.0,01:00:00,True,5
186141,EASTCHSTER/DYRE,5,2523024,1046466,2017-04-29 17:00:00,4662,0.000000e+00,0.000000e+00,0.0,17:00:00,True,5
186142,EASTCHSTER/DYRE,5,2523024,1046466,2017-04-29 21:00:00,4662,0.000000e+00,0.000000e+00,0.0,21:00:00,True,5
186143,EASTCHSTER/DYRE,5,2523024,1046466,2017-04-30 01:00:00,4662,0.000000e+00,0.000000e+00,0.0,01:00:00,True,5
186144,EASTCHSTER/DYRE,5,2523024,1046466,2017-04-30 05:00:00,4662,0.000000e+00,0.000000e+00,0.0,05:00:00,True,5
186145,EASTCHSTER/DYRE,5,2523024,1046466,2017-04-30 09:00:00,4662,0.000000e+00,0.000000e+00,0.0,09:00:00,True,5
186146,EASTCHSTER/DYRE,5,2523024,1046466,2017-04-30 13:00:00,4662,0.000000e+00,0.000000e+00,0.0,13:00:00,True,5
186147,EASTCHSTER/DYRE,5,2523024,1046466,2017-04-30 17:00:00,4662,0.000000e+00,0.000000e+00,0.0,17:00:00,True,5
186148,EASTCHSTER/DYRE,5,2523024,1046466,2017-04-30 21:00:00,4662,0.000000e+00,0.000000e+00,0.0,21:00:00,True,5
186149,EASTCHSTER/DYRE,5,2523024,1046466,2017-05-01 01:00:00,4662,0.000000e+00,0.000000e+00,0.0,01:00:00,False,5
559573,EASTCHSTER/DYRE,5,1339180,2561501,2017-05-14 05:00:00,4658,0.000000e+00,0.000000e+00,0.0,05:00:00,True,5
559617,EASTCHSTER/DYRE,5,5938157,7596902,2017-05-14 21:00:00,4659,0.000000e+00,0.000000e+00,0.0,21:00:00,True,5
559618,EASTCHSTER/DYRE,5,5938157,7596902,2017-05-15 01:00:00,4659,0.000000e+00,0.000000e+00,0.0,01:00:00,False,5
559619,EASTCHSTER/DYRE,5,5938157,7596902,2017-05-15 05:00:00,4659,0.000000e+00,0.000000e+00,0.0,05:00:00,False,5
559689,EASTCHSTER/DYRE,5,538949573,538463564,2017-05-13 13:00:00,4661,0.000000e+00,0.000000e+00,0.0,13:00:00,True,5
...,...,...,...,...,...,...,...,...,...,...,...,...
745791,EASTCHSTER/DYRE,5,538959966,538469732,2017-05-24 09:00:00,4661,7.280000e+02,1.220000e+02,0.0,09:00:00,False,5
559718,EASTCHSTER/DYRE,5,538954484,538466384,2017-05-18 09:00:00,4661,7.350000e+02,1.000000e+02,0.0,09:00:00,False,5
559660,EASTCHSTER/DYRE,5,2429934,2136453,2017-05-15 09:00:00,4660,7.390000e+02,1.740000e+02,0.0,09:00:00,False,5
186117,EASTCHSTER/DYRE,5,538937814,538455834,2017-05-02 09:00:00,4661,7.400000e+02,1.350000e+02,0.0,09:00:00,False,5
559712,EASTCHSTER/DYRE,5,538953085,538465501,2017-05-17 09:00:00,4661,7.420000e+02,1.570000e+02,0.0,09:00:00,False,5
186129,EASTCHSTER/DYRE,5,538940562,538457604,2017-05-04 09:00:00,4661,7.490000e+02,8.900000e+01,0.0,09:00:00,False,5
745751,EASTCHSTER/DYRE,5,2440896,2145733,2017-05-24 09:00:00,4660,7.500000e+02,2.080000e+02,0.0,09:00:00,False,5
559706,EASTCHSTER/DYRE,5,538951703,538464580,2017-05-16 09:00:00,4661,7.520000e+02,9.500000e+01,0.0,09:00:00,False,5
373551,EASTCHSTER/DYRE,5,538943462,538459394,2017-05-08 09:00:00,4661,7.550000e+02,1.140000e+02,0.0,09:00:00,False,5
186095,EASTCHSTER/DYRE,5,2420351,2128334,2017-05-05 09:00:00,4660,7.620000e+02,1.720000e+02,0.0,09:00:00,False,5
186071,EASTCHSTER/DYRE,5,2413897,2122813,2017-05-01 09:00:00,4660,7.620000e+02,1.820000e+02,0.0,09:00:00,False,5
745785,EASTCHSTER/DYRE,5,538958584,538468877,2017-05-23 09:00:00,4661,7.630000e+02,1.020000e+02,0.0,09:00:00,False,5
559700,EASTCHSTER/DYRE,5,538950337,538463669,2017-05-15 09:00:00,4661,7.640000e+02,1.050000e+02,0.0,09:00:00,False,5
373563,EASTCHSTER/DYRE,5,538946258,538461019,2017-05-10 09:00:00,4661,7.670000e+02,8.700000e+01,0.0,09:00:00,False,5
186135,EASTCHSTER/DYRE,5,538942062,538458506,2017-05-05 09:00:00,4661,7.790000e+02,7.500000e+01,0.0,09:00:00,False,5
373557,EASTCHSTER/DYRE,5,538944849,538460136,2017-05-09 09:00:00,4661,7.790000e+02,6.900000e+01,0.0,09:00:00,False,5
745745,EASTCHSTER/DYRE,5,2439334,2144374,2017-05-23 09:00:00,4660,7.800000e+02,1.790000e+02,0.0,09:00:00,False,5
186089,EASTCHSTER/DYRE,5,2418753,2126918,2017-05-04 09:00:00,4660,7.820000e+02,2.020000e+02,0.0,09:00:00,False,5
373511,EASTCHSTER/DYRE,5,2421949,2129825,2017-05-08 09:00:00,4660,7.870000e+02,1.760000e+02,0.0,09:00:00,False,5
373535,EASTCHSTER/DYRE,5,2428401,2135195,2017-05-12 09:00:00,4660,7.880000e+02,1.480000e+02,0.0,09:00:00,False,5
559678,EASTCHSTER/DYRE,5,2434811,2140476,2017-05-18 09:00:00,4660,7.900000e+02,1.590000e+02,0.0,09:00:00,False,5
186083,EASTCHSTER/DYRE,5,2417128,2125523,2017-05-03 09:00:00,4660,7.960000e+02,1.990000e+02,0.0,09:00:00,False,5
559672,EASTCHSTER/DYRE,5,2433176,2139100,2017-05-17 09:00:00,4660,7.980000e+02,1.350000e+02,0.0,09:00:00,False,5
373517,EASTCHSTER/DYRE,5,2423516,2131119,2017-05-09 09:00:00,4660,7.980000e+02,1.740000e+02,0.0,09:00:00,False,5
559666,EASTCHSTER/DYRE,5,2431533,2137803,2017-05-16 09:00:00,4660,8.000000e+02,2.150000e+02,0.0,09:00:00,False,5
373523,EASTCHSTER/DYRE,5,2425138,2132507,2017-05-10 09:00:00,4660,8.010000e+02,1.870000e+02,0.0,09:00:00,False,5
745763,EASTCHSTER/DYRE,5,2444093,2148447,2017-05-26 09:00:00,4660,8.100000e+02,2.210000e+02,0.0,09:00:00,False,5
373529,EASTCHSTER/DYRE,5,2426757,2133902,2017-05-11 09:00:00,4660,8.150000e+02,1.940000e+02,0.0,09:00:00,False,5
186077,EASTCHSTER/DYRE,5,2415496,2124131,2017-05-02 09:00:00,4660,8.190000e+02,1.950000e+02,0.0,09:00:00,False,5
186171,EASTCHSTER/DYRE,5,1560221425,1728055986,2017-05-05 13:00:00,4662,1.557696e+09,1.727009e+09,0.0,13:00:00,False,5

In [65]:
df.iloc[190820:190840]

,STATION,LINENAME,ENTRIES,EXITS,parsed_datetime,station_id,entry_num,exit_num,station_diff,time,Weekend,line_sort
190820,EASTCHSTER/DYRE,5,2524506,1046984,2017-05-03 13:00:00,4662,5.300000e+01,6.000000e+00,0.0,13:00:00,False,5
190821,EASTCHSTER/DYRE,5,2524589,1047045,2017-05-03 17:00:00,4662,8.300000e+01,6.100000e+01,0.0,17:00:00,False,5
190822,EASTCHSTER/DYRE,5,2524663,1047143,2017-05-03 21:00:00,4662,7.400000e+01,9.800000e+01,0.0,21:00:00,False,5
190823,EASTCHSTER/DYRE,5,2524674,1047160,2017-05-04 01:00:00,4662,1.100000e+01,1.700000e+01,0.0,01:00:00,False,5
190824,EASTCHSTER/DYRE,5,2524680,1047163,2017-05-04 05:00:00,4662,6.000000e+00,3.000000e+00,0.0,05:00:00,False,5
190825,EASTCHSTER/DYRE,5,2525010,1047200,2017-05-04 09:00:00,4662,3.300000e+02,3.700000e+01,0.0,09:00:00,False,5
190826,EASTCHSTER/DYRE,5,2525075,1047213,2017-05-04 13:00:00,4662,6.500000e+01,1.300000e+01,0.0,13:00:00,False,5
190827,EASTCHSTER/DYRE,5,1560221483,1728055978,2017-05-05 09:00:00,4662,1.557696e+09,1.727009e+09,0.0,09:00:00,False,5
190828,EASTCHSTER/DYRE,5,1560221425,1728055986,2017-05-05 13:00:00,4662,-5.800000e+01,8.000000e+00,0.0,13:00:00,False,5
190829,EASTCHSTER/DYRE,5,1560221334,1728056067,2017-05-05 17:00:00,4662,-9.100000e+01,8.100000e+01,0.0,17:00:00,False,5
190830,EASTCHSTER/DYRE,5,1560221276,1728056160,2017-05-05 21:00:00,4662,-5.800000e+01,9.300000e+01,0.0,21:00:00,False,5
190831,ST. GEORGE,1,1026199,179,2017-04-29 04:00:00,4663,5.000000e+00,0.000000e+00,0.0,04:00:00,True,1
190832,ST. GEORGE,1,1026224,179,2017-04-29 08:00:00,4663,2.500000e+01,0.000000e+00,0.0,08:00:00,True,1
190833,ST. GEORGE,1,1026268,179,2017-04-29 12:00:00,4663,4.400000e+01,0.000000e+00,0.0,12:00:00,True,1
190834,ST. GEORGE,1,1026303,179,2017-04-29 16:00:00,4663,3.500000e+01,0.000000e+00,0.0,16:00:00,True,1
190835,ST. GEORGE,1,1026334,179,2017-04-29 20:00:00,4663,3.100000e+01,0.000000e+00,0.0,20:00:00,True,1
190836,ST. GEORGE,1,1026354,179,2017-04-30 00:00:00,4663,2.000000e+01,0.000000e+00,0.0,00:00:00,True,1
190837,ST. GEORGE,1,1026357,179,2017-04-30 04:00:00,4663,3.000000e+00,0.000000e+00,0.0,04:00:00,True,1
190838,ST. GEORGE,1,1026378,179,2017-04-30 08:00:00,4663,2.100000e+01,0.000000e+00,0.0,08:00:00,True,1
190839,ST. GEORGE,1,1026410,179,2017-04-30 12:00:00,4663,3.200000e+01,0.000000e+00,0.0,12:00:00,True,1

In [104]:
df[df.STATION == '72 ST'].sort_values(by='entry_num')

,STATION,LINENAME,ENTRIES,EXITS,parsed_datetime,station_id,entry_num,exit_num,station_diff,time,Weekend,line_sort
316937,72 ST,123,0,1968,2017-05-12 17:00:00,3250,0.0,0.000000e+00,0.0,17:00:00,False,123
316809,72 ST,123,6200,0,2017-05-11 09:00:00,3247,0.0,0.000000e+00,0.0,09:00:00,False,123
316808,72 ST,123,6200,0,2017-05-11 05:00:00,3247,0.0,0.000000e+00,0.0,05:00:00,False,123
316807,72 ST,123,6200,0,2017-05-11 01:00:00,3247,0.0,0.000000e+00,0.0,01:00:00,False,123
316803,72 ST,123,6196,0,2017-05-10 09:00:00,3247,0.0,0.000000e+00,0.0,09:00:00,False,123
316802,72 ST,123,6196,0,2017-05-10 05:00:00,3247,0.0,0.000000e+00,0.0,05:00:00,False,123
316801,72 ST,123,6196,0,2017-05-10 01:00:00,3247,0.0,0.000000e+00,0.0,01:00:00,False,123
316798,72 ST,123,6194,0,2017-05-09 13:00:00,3247,0.0,0.000000e+00,0.0,13:00:00,False,123
316810,72 ST,123,6200,0,2017-05-11 13:00:00,3247,0.0,0.000000e+00,0.0,13:00:00,False,123
316797,72 ST,123,6194,0,2017-05-09 09:00:00,3247,0.0,0.000000e+00,0.0,09:00:00,False,123
316795,72 ST,123,6194,0,2017-05-09 01:00:00,3247,0.0,0.000000e+00,0.0,01:00:00,False,123
316793,72 ST,123,6193,0,2017-05-08 17:00:00,3247,0.0,0.000000e+00,0.0,17:00:00,False,123
316792,72 ST,123,6193,0,2017-05-08 13:00:00,3247,0.0,0.000000e+00,0.0,13:00:00,False,123
316791,72 ST,123,6193,0,2017-05-08 09:00:00,3247,0.0,0.000000e+00,0.0,09:00:00,False,123
316790,72 ST,123,6193,0,2017-05-08 05:00:00,3247,0.0,0.000000e+00,0.0,05:00:00,False,123
316789,72 ST,123,6193,0,2017-05-08 01:00:00,3247,0.0,0.000000e+00,0.0,01:00:00,False,123
316788,72 ST,123,6193,0,2017-05-07 21:00:00,3247,0.0,0.000000e+00,0.0,21:00:00,True,123
316796,72 ST,123,6194,0,2017-05-09 05:00:00,3247,0.0,0.000000e+00,0.0,05:00:00,False,123
316786,72 ST,123,6192,0,2017-05-07 13:00:00,3247,0.0,0.000000e+00,0.0,13:00:00,True,123
316811,72 ST,123,6200,0,2017-05-11 17:00:00,3247,0.0,0.000000e+00,0.0,17:00:00,False,123
316814,72 ST,123,6202,0,2017-05-12 05:00:00,3247,0.0,0.000000e+00,0.0,05:00:00,False,123
316831,72 ST,123,0,1646,2017-05-08 09:00:00,3248,0.0,0.000000e+00,0.0,09:00:00,False,123
316830,72 ST,123,0,1646,2017-05-08 05:00:00,3248,0.0,0.000000e+00,0.0,05:00:00,False,123
316829,72 ST,123,0,1646,2017-05-08 01:00:00,3248,0.0,0.000000e+00,0.0,01:00:00,False,123
316828,72 ST,123,0,1646,2017-05-07 21:00:00,3248,0.0,0.000000e+00,0.0,21:00:00,True,123
316827,72 ST,123,0,1646,2017-05-07 17:00:00,3248,0.0,0.000000e+00,0.0,17:00:00,True,123
316826,72 ST,123,0,1646,2017-05-07 13:00:00,3248,0.0,0.000000e+00,0.0,13:00:00,True,123
316825,72 ST,123,0,1646,2017-05-07 09:00:00,3248,0.0,0.000000e+00,0.0,09:00:00,True,123
316813,72 ST,123,6202,0,2017-05-12 01:00:00,3247,0.0,0.000000e+00,0.0,01:00:00,False,123
316824,72 ST,123,0,1646,2017-05-07 05:00:00,3248,0.0,0.000000e+00,0.0,05:00:00,True,123
...,...,...,...,...,...,...,...,...,...,...,...,...
129029,72 ST,123,9070889,5571142,2017-05-02 21:00:00,3237,1126.0,7.950000e+02,0.0,21:00:00,False,123
129038,72 ST,123,9077189,5574335,2017-05-04 09:00:00,3237,1127.0,4.040000e+02,0.0,09:00:00,False,123
316400,72 ST,123,9099895,5588145,2017-05-09 21:00:00,3237,1129.0,9.240000e+02,0.0,21:00:00,False,123
129035,72 ST,123,9075619,5573713,2017-05-03 21:00:00,3237,1129.0,8.920000e+02,0.0,21:00:00,False,123
316417,72 ST,123,9113113,5595073,2017-05-12 17:00:00,3237,1134.0,6.120000e+02,0.0,17:00:00,False,123
316409,72 ST,123,9106351,5591323,2017-05-11 09:00:00,3237,1135.0,4.000000e+02,0.0,09:00:00,False,123
503353,72 ST,123,9129899,5606495,2017-05-16 21:00:00,3237,1141.0,7.510000e+02,0.0,21:00:00,False,123
503668,72 ST,123,18256711,7601277,2017-05-16 17:00:00,3245,1143.0,2.940000e+02,0.0,17:00:00,False,123
689209,72 ST,123,9162142,5626132,2017-05-24 09:00:00,3237,1145.0,4.050000e+02,0.0,09:00:00,False,123
689197,72 ST,123,9152843,5620893,2017-05-22 09:00:00,3237,1147.0,4.130000e+02,0.0,09:00:00,False,123
316720,72 ST,123,18232292,7592450,2017-05-09 21:00:00,3245,1147.0,3.950000e+02,0.0,21:00:00,False,123
503721,72 ST,123,16066758,5188363,2017-05-18 21:00:00,3246,1149.0,2.160000e+02,0.0,21:00:00,False,123
503370,72 ST,123,9143110,5613587,2017-05-19 17:00:00,3237,1157.0,6.580000e+02,0.0,17:00:00,False,123
689206,72 ST,123,9160470,5625431,2017-05-23 21:00:00,3237,1157.0,1.004000e+03,0.0,21:00:00,False,123
316399,72 ST,123,9098766,5587221,2017-05-09 17:00:00,3237,1158.0,6.080000e+02,0.0,17:00:00,False,123
316406,72 ST,123,9104776,5590696,2017-05-10 21:00:00,3237,1158.0,8.410000e+02,0.0,21:00:00,False,123
689223,72 ST,123,9172986,5632932,2017-05-26 17:00:00,3237,1161.0,7.320000e+02,0.0,17:00:00,False,123
689205,72 ST,123,9159313,5624427,2017-05-23 17:00:00,3237,1166.0,7.250000e+02,0.0,17:00:00,False,123
503359,72 ST,123,9134742,5609055,2017-05-17 21:00:00,3237,1168.0,7.620000e+02,0.0,21:00:00,False,123
503687,72 ST,123,18270603,7606570,2017-05-19 21:00:00,3245,1173.0,6.880000e+02,0.0,21:00:00,False,123
503708,72 ST,123,16057125,5186055,2017-05-16 17:00:00,3246,1174.0,2.110000e+02,0.0,17:00:00,False,123
503365,72 ST,123,9139510,5611716,2017-05-18 21:00:00,3237,1177.0,8.740000e+02,0.0,21:00:00,False,123
503686,72 ST,123,18269430,7605882,2017-05-19 17:00:00,3245,1178.0,5.520000e+02,0.0,17:00:00,False,123
129041,72 ST,123,9080416,5576132,2017-05-04 21:00:00,3237,1179.0,7.970000e+02,0.0,21:00:00,False,123
503681,72 ST,123,18266315,7604631,2017-05-18 21:00:00,3245,1185.0,3.750000e+02,0.0,21:00:00,False,123
418688,72 ST,BC,2506031,1337364,2017-05-18 20:00:00,1090,1196.0,5.430000e+02,0.0,20:00:00,False,BC
316403,72 ST,123,9101569,5588834,2017-05-10 09:00:00,3237,1213.0,4.110000e+02,0.0,09:00:00,False,123
503350,72 ST,123,9126736,5604696,2017-05-16 09:00:00,3237,1284.0,4.260000e+02,0.0,09:00:00,False,123
503727,72 ST,123,16071667,5189559,2017-05-19 21:00:00,3246,1296.0,2.870000e+02,0.0,21:00:00,False,123
129212,72 ST,123,691259656,1758148759,2017-04-30 17:00:00,3242,683154377.0,1.751213e+09,0.0,17:00:00,True,123

In [105]:
df.iloc[132440:132450]

,STATION,LINENAME,ENTRIES,EXITS,parsed_datetime,station_id,entry_num,exit_num,station_diff,time,Weekend,line_sort
132440,137 ST CITY COL,1,3617060,9188915,2017-04-29 13:00:00,3323,204.0,92.0,0.0,13:00:00,True,1
132441,137 ST CITY COL,1,3617277,9189092,2017-04-29 17:00:00,3323,217.0,177.0,0.0,17:00:00,True,1
132442,137 ST CITY COL,1,3617399,9189321,2017-04-29 21:00:00,3323,122.0,229.0,0.0,21:00:00,True,1
132443,137 ST CITY COL,1,3617484,9189515,2017-04-30 01:00:00,3323,85.0,194.0,0.0,01:00:00,True,1
132444,137 ST CITY COL,1,3617490,9189590,2017-04-30 05:00:00,3323,6.0,75.0,0.0,05:00:00,True,1
132445,137 ST CITY COL,1,3617537,9189616,2017-04-30 09:00:00,3323,47.0,26.0,0.0,09:00:00,True,1
132446,137 ST CITY COL,1,3617674,9189697,2017-04-30 13:00:00,3323,137.0,81.0,0.0,13:00:00,True,1
132447,137 ST CITY COL,1,3617820,9189857,2017-04-30 17:00:00,3323,146.0,160.0,0.0,17:00:00,True,1
132448,137 ST CITY COL,1,3617924,9190070,2017-04-30 21:00:00,3323,104.0,213.0,0.0,21:00:00,True,1
132449,137 ST CITY COL,1,3617961,9190213,2017-05-01 01:00:00,3323,37.0,143.0,0.0,01:00:00,False,1

In [106]:
pre_removaldf = df

In [107]:
# DROPPING ENTRIES AND EXIT OUTLIERS
df = df.drop(df[df.entry_num > 10000].index)
df = df.drop(df[df.exit_num > 10000].index)

df.reset_index(drop=True)

,STATION,LINENAME,ENTRIES,EXITS,parsed_datetime,station_id,entry_num,exit_num,station_diff,time,Weekend,line_sort
0,59 ST,NQR456W,6157810,2085353,2017-04-29 08:00:00,0,33.0,34.0,0.0,08:00:00,True,456NQRW
1,59 ST,NQR456W,6157963,2085453,2017-04-29 12:00:00,0,153.0,100.0,0.0,12:00:00,True,456NQRW
2,59 ST,NQR456W,6158212,2085529,2017-04-29 16:00:00,0,249.0,76.0,0.0,16:00:00,True,456NQRW
3,59 ST,NQR456W,6158521,2085589,2017-04-29 20:00:00,0,309.0,60.0,0.0,20:00:00,True,456NQRW
4,59 ST,NQR456W,6158637,2085612,2017-04-30 00:00:00,0,116.0,23.0,0.0,00:00:00,True,456NQRW
5,59 ST,NQR456W,6158654,2085617,2017-04-30 04:00:00,0,17.0,5.0,0.0,04:00:00,True,456NQRW
6,59 ST,NQR456W,6158661,2085641,2017-04-30 08:00:00,0,7.0,24.0,0.0,08:00:00,True,456NQRW
7,59 ST,NQR456W,6158703,2085730,2017-04-30 12:00:00,0,42.0,89.0,0.0,12:00:00,True,456NQRW
8,59 ST,NQR456W,6158797,2085785,2017-04-30 16:00:00,0,94.0,55.0,0.0,16:00:00,True,456NQRW
9,59 ST,NQR456W,6159015,2085824,2017-04-30 20:00:00,0,218.0,39.0,0.0,20:00:00,True,456NQRW
10,59 ST,NQR456W,6159107,2085842,2017-05-01 00:00:00,0,92.0,18.0,0.0,00:00:00,False,456NQRW
11,59 ST,NQR456W,6159116,2085849,2017-05-01 04:00:00,0,9.0,7.0,0.0,04:00:00,False,456NQRW
12,59 ST,NQR456W,6159166,2085976,2017-05-01 08:00:00,0,50.0,127.0,0.0,08:00:00,False,456NQRW
13,59 ST,NQR456W,6159331,2086218,2017-05-01 12:00:00,0,165.0,242.0,0.0,12:00:00,False,456NQRW
14,59 ST,NQR456W,6159595,2086299,2017-05-01 16:00:00,0,264.0,81.0,0.0,16:00:00,False,456NQRW
15,59 ST,NQR456W,6160374,2086358,2017-05-01 20:00:00,0,779.0,59.0,0.0,20:00:00,False,456NQRW
16,59 ST,NQR456W,6160508,2086374,2017-05-02 00:00:00,0,134.0,16.0,0.0,00:00:00,False,456NQRW
17,59 ST,NQR456W,6160514,2086379,2017-05-02 04:00:00,0,6.0,5.0,0.0,04:00:00,False,456NQRW
18,59 ST,NQR456W,6160555,2086499,2017-05-02 08:00:00,0,41.0,120.0,0.0,08:00:00,False,456NQRW
19,59 ST,NQR456W,6160711,2086769,2017-05-02 12:00:00,0,156.0,270.0,0.0,12:00:00,False,456NQRW
20,59 ST,NQR456W,6161012,2086835,2017-05-02 16:00:00,0,301.0,66.0,0.0,16:00:00,False,456NQRW
21,59 ST,NQR456W,6161830,2086908,2017-05-02 20:00:00,0,818.0,73.0,0.0,20:00:00,False,456NQRW
22,59 ST,NQR456W,6162061,2086933,2017-05-03 00:00:00,0,231.0,25.0,0.0,00:00:00,False,456NQRW
23,59 ST,NQR456W,6162082,2086939,2017-05-03 04:00:00,0,21.0,6.0,0.0,04:00:00,False,456NQRW
24,59 ST,NQR456W,6162129,2087070,2017-05-03 08:00:00,0,47.0,131.0,0.0,08:00:00,False,456NQRW
25,59 ST,NQR456W,6162287,2087324,2017-05-03 12:00:00,0,158.0,254.0,0.0,12:00:00,False,456NQRW
26,59 ST,NQR456W,6162575,2087391,2017-05-03 16:00:00,0,288.0,67.0,0.0,16:00:00,False,456NQRW
27,59 ST,NQR456W,6163254,2087451,2017-05-03 20:00:00,0,679.0,60.0,0.0,20:00:00,False,456NQRW
28,59 ST,NQR456W,6163517,2087485,2017-05-04 00:00:00,0,263.0,34.0,0.0,00:00:00,False,456NQRW
29,59 ST,NQR456W,6163534,2087487,2017-05-04 04:00:00,0,17.0,2.0,0.0,04:00:00,False,456NQRW
...,...,...,...,...,...,...,...,...,...,...,...,...
747481,RIT-ROOSEVELT,R,5554,299,2017-05-22 05:00:00,4705,0.0,0.0,0.0,05:00:00,False,R
747482,RIT-ROOSEVELT,R,5554,299,2017-05-22 09:00:00,4705,0.0,0.0,0.0,09:00:00,False,R
747483,RIT-ROOSEVELT,R,5554,299,2017-05-22 13:00:00,4705,0.0,0.0,0.0,13:00:00,False,R
747484,RIT-ROOSEVELT,R,5554,299,2017-05-22 17:00:00,4705,0.0,0.0,0.0,17:00:00,False,R
747485,RIT-ROOSEVELT,R,5554,299,2017-05-22 21:00:00,4705,0.0,0.0,0.0,21:00:00,False,R
747486,RIT-ROOSEVELT,R,5554,299,2017-05-23 01:00:00,4705,0.0,0.0,0.0,01:00:00,False,R
747487,RIT-ROOSEVELT,R,5554,299,2017-05-23 05:00:00,4705,0.0,0.0,0.0,05:00:00,False,R
747488,RIT-ROOSEVELT,R,5554,299,2017-05-23 08:18:52,4705,0.0,0.0,0.0,08:18:52,False,R
747489,RIT-ROOSEVELT,R,5554,299,2017-05-23 09:00:00,4705,0.0,0.0,0.0,09:00:00,False,R
747490,RIT-ROOSEVELT,R,5554,299,2017-05-23 13:00:00,4705,0.0,0.0,0.0,13:00:00,False,R
747491,RIT-ROOSEVELT,R,5554,299,2017-05-23 17:00:00,4705,0.0,0.0,0.0,17:00:00,False,R
747492,RIT-ROOSEVELT,R,5554,299,2017-05-23 21:00:00,4705,0.0,0.0,0.0,21:00:00,False,R
747493,RIT-ROOSEVELT,R,5554,299,2017-05-24 01:00:00,4705,0.0,0.0,0.0,01:00:00,False,R
747494,RIT-ROOSEVELT,R,5554,299,2017-05-24 05:00:00,4705,0.0,0.0,0.0,05:00:00,False,R
747495,RIT-ROOSEVELT,R,5554,299,2017-05-24 09:00:00,4705,0.0,0.0,0.0,09:00:00,False,R
747496,RIT-ROOSEVELT,R,5554,299,2017-05-24 13:00:00,4705,0.0,0.0,0.0,13:00:00,False,R
747497,RIT-ROOSEVELT,R,5554,299,2017-05-24 17:00:00,4705,0.0,0.0,0.0,17:00:00,False,R
747498,RIT-ROOSEVELT,R,5554,299,2017-05-24 21:00:00,4705,0.0,0.0,0.0,21:00:00,False,R
747499,RIT-ROOSEVELT,R,5554,299,2017-05-25 01:00:00,4705,0.0,0.0,0.0,01:00:00,False,R
747500,RIT-ROOSEVELT,R,5554,299,2017-05-25 05:00:00,4705,0.0,0.0,0.0,05:00:00,False,R
747501,RIT-ROOSEVELT,R,5554,299,2017-05-25 09:00:00,4705,0.0,0.0,0.0,09:00:00,False,R
747502,RIT-ROOSEVELT,R,5554,299,2017-05-25 13:00:00,4705,0.0,0.0,0.0,13:00:00,False,R
747503,RIT-ROOSEVELT,R,5554,299,2017-05-25 17:00:00,4705,0.0,0.0,0.0,17:00:00,False,R
747504,RIT-ROOSEVELT,R,5554,299,2017-05-25 21:00:00,4705,0.0,0.0,0.0,21:00:00,False,R
747505,RIT-ROOSEVELT,R,5554,299,2017-05-26 01:00:00,4705,0.0,0.0,0.0,01:00:00,False,R
747506,RIT-ROOSEVELT,R,5554,299,2017-05-26 05:00:00,4705,0.0,0.0,0.0,05:00:00,False,R
747507,RIT-ROOSEVELT,R,5554,299,2017-05-26 09:00:00,4705,0.0,0.0,0.0,09:00:00,False,R
747508,RIT-ROOSEVELT,R,5554,299,2017-05-26 13:00:00,4705,0.0,0.0,0.0,13:00:00,False,R
747509,RIT-ROOSEVELT,R,5554,299,2017-05-26 17:00:00,4705,0.0,0.0,0.0,17:00:00,False,R
747510,RIT-ROOSEVELT,R,5554,299,2017-05-26 21:00:00,4705,0.0,0.0,0.0,21:00:00,False,R

In [1]:
final_df = df.groupby(['STATION','line_sort'])[['entry_num', 'exit_num']].sum().sort_values(by=['entry_num'])
final_df

NameError: name 'df' is not defined

In [ ]:
# df['abs_entry_num'] = df.apply(lambda row: abs(row.entry_num), axis=1)
# df['abs_exit_num'] = df.apply(lambda row: abs(row.exit_num), axis=1)
# df.sort_values(['abs_entry_num'], ascending=[False])

In [ ]:
# df.loc[df.station_id == 3645, :]

In [ ]:
# df.station_id.value_counts().sort_values()

In [ ]:
# df.loc[df.station_id == 2620, :]

In [ ]:
# groupedstations_df = df.groupby(['station_id','STATION'])[['entry_num']].sum()
# groupedstations_df.sort_values(['entry_num'], ascending=[False])