In [1]:
import pandas as pd
import numpy as np
import csv
import re
import matplotlib.pyplot as plt
%matplotlib inline

import dateutil.parser
from dateutil import parser
from datetime import datetime
df = pd.read_csv('http://web.mta.info/developers/data/nyct/turnstile/turnstile_180106.txt')
df['EXITS'] = df["EXITS                                                               "]
df.drop("EXITS                                                               ", axis = 1, inplace = True)
df

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/30/2017,03:00:00,REGULAR,6463109,2187558
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/30/2017,07:00:00,REGULAR,6463119,2187567
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/30/2017,11:00:00,REGULAR,6463178,2187654
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/30/2017,15:00:00,REGULAR,6463373,2187736
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/30/2017,19:00:00,REGULAR,6463712,2187803
5,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/30/2017,23:00:00,REGULAR,6463887,2187833
6,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/31/2017,03:00:00,REGULAR,6463926,2187844
7,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/31/2017,07:00:00,REGULAR,6463938,2187856
8,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/31/2017,11:00:00,REGULAR,6463980,2187919
9,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/31/2017,15:00:00,REGULAR,6464138,2187969
10,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/31/2017,19:00:00,REGULAR,6464337,2188024
11,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/31/2017,23:00:00,REGULAR,6464443,2188049
12,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/01/2018,03:00:00,REGULAR,6464475,2188055
13,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/01/2018,07:00:00,REGULAR,6464491,2188064
14,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/01/2018,11:00:00,REGULAR,6464517,2188106
15,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/01/2018,15:00:00,REGULAR,6464623,2188146
16,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/01/2018,19:00:00,REGULAR,6464806,2188192
17,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/01/2018,23:00:00,REGULAR,6464907,2188209
18,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/02/2018,03:00:00,REGULAR,6464919,2188214
19,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/02/2018,07:00:00,REGULAR,6464934,2188247
20,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/02/2018,11:00:00,REGULAR,6465085,2188505
21,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/02/2018,15:00:00,REGULAR,6465297,2188572
22,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/02/2018,19:00:00,REGULAR,6466098,2188659
23,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/02/2018,23:00:00,REGULAR,6466375,2188704
24,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/03/2018,03:00:00,REGULAR,6466403,2188707
25,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/03/2018,07:00:00,REGULAR,6466420,2188747
26,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/03/2018,11:00:00,REGULAR,6466581,2189060
27,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/03/2018,15:00:00,REGULAR,6466816,2189132
28,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/03/2018,19:00:00,REGULAR,6467618,2189215
29,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/03/2018,23:00:00,REGULAR,6467957,2189246
...,...,...,...,...,...,...,...,...,...,...,...
200635,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/01/2018,00:00:00,REGULAR,2446008,27423
200636,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/01/2018,04:00:00,REGULAR,2446008,27423
200637,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/01/2018,08:00:00,REGULAR,2446008,27423
200638,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/01/2018,12:00:00,REGULAR,2446008,27423
200639,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/01/2018,16:00:00,REGULAR,2446008,27423
200640,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/01/2018,20:00:00,REGULAR,2446008,27423
200641,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/02/2018,00:00:00,REGULAR,2446008,27423
200642,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/02/2018,04:00:00,REGULAR,2446008,27423
200643,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/02/2018,08:00:00,REGULAR,2446008,27423
200644,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/02/2018,12:00:00,REGULAR,2446198,27424
200645,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/02/2018,16:00:00,REGULAR,2446549,27425
200646,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/02/2018,20:00:00,REGULAR,2446730,27432
200647,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/03/2018,00:00:00,REGULAR,2446786,27434
200648,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/03/2018,04:00:00,REGULAR,2446789,27435
200649,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/03/2018,08:00:00,REGULAR,2446889,27435
200650,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/03/2018,12:00:00,REGULAR,2447230,27435
200651,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/03/2018,16:00:00,REGULAR,2447501,27437
200652,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/03/2018,20:00:00,REGULAR,2447711,27440
200653,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/04/2018,00:00:00,REGULAR,2447795,27443
200654,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/04/2018,04:00:00,REGULAR,2447807,27444
200655,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/04/2018,08:00:00,REGULAR,2447853,27444
200656,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/04/2018,12:00:00,REGULAR,2447967,27449
200657,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/04/2018,16:00:00,REGULAR,2447984,27466
200658,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/04/2018,20:00:00,REGULAR,2448051,27538
200659,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/05/2018,00:00:00,REGULAR,2448078,27545
200660,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/05/2018,04:00:00,REGULAR,2448082,27552
200661,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/05/2018,08:00:00,REGULAR,2448175,27559
200662,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/05/2018,12:00:00,REGULAR,2448484,27568
200663,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/05/2018,16:00:00,REGULAR,2448641,27578
200664,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/05/2018,20:00:00,REGULAR,2448770,27578

In [2]:
df['new_key'] = df[['C/A', 'UNIT', 'SCP', 'STATION']].apply(lambda x: ' '.join(x), axis=1)
df['date_time'] = (df[['DATE', 'TIME']].apply(lambda x: ' '.join(x), axis=1).str.replace('/','-'))
df['parsed_datetime'] = df.apply(lambda row: parser.parse(row.date_time), axis=1)
# df['date'] = (df['parsed_datetime'].apply(lambda x: x.date()))
# df['entries_num'] = int(df['ENTRIES'])-int(df['ENTRIES'][1:])
df

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS,new_key,date_time,parsed_datetime
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/30/2017,03:00:00,REGULAR,6463109,2187558,A002 R051 02-00-00 59 ST,12-30-2017 03:00:00,2017-12-30 03:00:00
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/30/2017,07:00:00,REGULAR,6463119,2187567,A002 R051 02-00-00 59 ST,12-30-2017 07:00:00,2017-12-30 07:00:00
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/30/2017,11:00:00,REGULAR,6463178,2187654,A002 R051 02-00-00 59 ST,12-30-2017 11:00:00,2017-12-30 11:00:00
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/30/2017,15:00:00,REGULAR,6463373,2187736,A002 R051 02-00-00 59 ST,12-30-2017 15:00:00,2017-12-30 15:00:00
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/30/2017,19:00:00,REGULAR,6463712,2187803,A002 R051 02-00-00 59 ST,12-30-2017 19:00:00,2017-12-30 19:00:00
5,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/30/2017,23:00:00,REGULAR,6463887,2187833,A002 R051 02-00-00 59 ST,12-30-2017 23:00:00,2017-12-30 23:00:00
6,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/31/2017,03:00:00,REGULAR,6463926,2187844,A002 R051 02-00-00 59 ST,12-31-2017 03:00:00,2017-12-31 03:00:00
7,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/31/2017,07:00:00,REGULAR,6463938,2187856,A002 R051 02-00-00 59 ST,12-31-2017 07:00:00,2017-12-31 07:00:00
8,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/31/2017,11:00:00,REGULAR,6463980,2187919,A002 R051 02-00-00 59 ST,12-31-2017 11:00:00,2017-12-31 11:00:00
9,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/31/2017,15:00:00,REGULAR,6464138,2187969,A002 R051 02-00-00 59 ST,12-31-2017 15:00:00,2017-12-31 15:00:00
10,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/31/2017,19:00:00,REGULAR,6464337,2188024,A002 R051 02-00-00 59 ST,12-31-2017 19:00:00,2017-12-31 19:00:00
11,A002,R051,02-00-00,59 ST,NQR456W,BMT,12/31/2017,23:00:00,REGULAR,6464443,2188049,A002 R051 02-00-00 59 ST,12-31-2017 23:00:00,2017-12-31 23:00:00
12,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/01/2018,03:00:00,REGULAR,6464475,2188055,A002 R051 02-00-00 59 ST,01-01-2018 03:00:00,2018-01-01 03:00:00
13,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/01/2018,07:00:00,REGULAR,6464491,2188064,A002 R051 02-00-00 59 ST,01-01-2018 07:00:00,2018-01-01 07:00:00
14,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/01/2018,11:00:00,REGULAR,6464517,2188106,A002 R051 02-00-00 59 ST,01-01-2018 11:00:00,2018-01-01 11:00:00
15,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/01/2018,15:00:00,REGULAR,6464623,2188146,A002 R051 02-00-00 59 ST,01-01-2018 15:00:00,2018-01-01 15:00:00
16,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/01/2018,19:00:00,REGULAR,6464806,2188192,A002 R051 02-00-00 59 ST,01-01-2018 19:00:00,2018-01-01 19:00:00
17,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/01/2018,23:00:00,REGULAR,6464907,2188209,A002 R051 02-00-00 59 ST,01-01-2018 23:00:00,2018-01-01 23:00:00
18,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/02/2018,03:00:00,REGULAR,6464919,2188214,A002 R051 02-00-00 59 ST,01-02-2018 03:00:00,2018-01-02 03:00:00
19,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/02/2018,07:00:00,REGULAR,6464934,2188247,A002 R051 02-00-00 59 ST,01-02-2018 07:00:00,2018-01-02 07:00:00
20,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/02/2018,11:00:00,REGULAR,6465085,2188505,A002 R051 02-00-00 59 ST,01-02-2018 11:00:00,2018-01-02 11:00:00
21,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/02/2018,15:00:00,REGULAR,6465297,2188572,A002 R051 02-00-00 59 ST,01-02-2018 15:00:00,2018-01-02 15:00:00
22,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/02/2018,19:00:00,REGULAR,6466098,2188659,A002 R051 02-00-00 59 ST,01-02-2018 19:00:00,2018-01-02 19:00:00
23,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/02/2018,23:00:00,REGULAR,6466375,2188704,A002 R051 02-00-00 59 ST,01-02-2018 23:00:00,2018-01-02 23:00:00
24,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/03/2018,03:00:00,REGULAR,6466403,2188707,A002 R051 02-00-00 59 ST,01-03-2018 03:00:00,2018-01-03 03:00:00
25,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/03/2018,07:00:00,REGULAR,6466420,2188747,A002 R051 02-00-00 59 ST,01-03-2018 07:00:00,2018-01-03 07:00:00
26,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/03/2018,11:00:00,REGULAR,6466581,2189060,A002 R051 02-00-00 59 ST,01-03-2018 11:00:00,2018-01-03 11:00:00
27,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/03/2018,15:00:00,REGULAR,6466816,2189132,A002 R051 02-00-00 59 ST,01-03-2018 15:00:00,2018-01-03 15:00:00
28,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/03/2018,19:00:00,REGULAR,6467618,2189215,A002 R051 02-00-00 59 ST,01-03-2018 19:00:00,2018-01-03 19:00:00
29,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/03/2018,23:00:00,REGULAR,6467957,2189246,A002 R051 02-00-00 59 ST,01-03-2018 23:00:00,2018-01-03 23:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200635,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/01/2018,00:00:00,REGULAR,2446008,27423,TRAM2 R469 00-03-01 RIT-ROOSEVELT,01-01-2018 00:00:00,2018-01-01 00:00:00
200636,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/01/2018,04:00:00,REGULAR,2446008,27423,TRAM2 R469 00-03-01 RIT-ROOSEVELT,01-01-2018 04:00:00,2018-01-01 04:00:00
200637,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/01/2018,08:00:00,REGULAR,2446008,27423,TRAM2 R469 00-03-01 RIT-ROOSEVELT,01-01-2018 08:00:00,2018-01-01 08:00:00
200638,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/01/2018,12:00:00,REGULAR,2446008,27423,TRAM2 R469 00-03-01 RIT-ROOSEVELT,01-01-2018 12:00:00,2018-01-01 12:00:00
200639,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/01/2018,16:00:00,REGULAR,2446008,27423,TRAM2 R469 00-03-01 RIT-ROOSEVELT,01-01-2018 16:00:00,2018-01-01 16:00:00
200640,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/01/2018,20:00:00,REGULAR,2446008,27423,TRAM2 R469 00-03-01 RIT-ROOSEVELT,01-01-2018 20:00:00,2018-01-01 20:00:00
200641,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/02/2018,00:00:00,REGULAR,2446008,27423,TRAM2 R469 00-03-01 RIT-ROOSEVELT,01-02-2018 00:00:00,2018-01-02 00:00:00
200642,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/02/2018,04:00:00,REGULAR,2446008,27423,TRAM2 R469 00-03-01 RIT-ROOSEVELT,01-02-2018 04:00:00,2018-01-02 04:00:00
200643,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/02/2018,08:00:00,REGULAR,2446008,27423,TRAM2 R469 00-03-01 RIT-ROOSEVELT,01-02-2018 08:00:00,2018-01-02 08:00:00
200644,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/02/2018,12:00:00,REGULAR,2446198,27424,TRAM2 R469 00-03-01 RIT-ROOSEVELT,01-02-2018 12:00:00,2018-01-02 12:00:00
200645,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/02/2018,16:00:00,REGULAR,2446549,27425,TRAM2 R469 00-03-01 RIT-ROOSEVELT,01-02-2018 16:00:00,2018-01-02 16:00:00
200646,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/02/2018,20:00:00,REGULAR,2446730,27432,TRAM2 R469 00-03-01 RIT-ROOSEVELT,01-02-2018 20:00:00,2018-01-02 20:00:00
200647,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/03/2018,00:00:00,REGULAR,2446786,27434,TRAM2 R469 00-03-01 RIT-ROOSEVELT,01-03-2018 00:00:00,2018-01-03 00:00:00
200648,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/03/2018,04:00:00,REGULAR,2446789,27435,TRAM2 R469 00-03-01 RIT-ROOSEVELT,01-03-2018 04:00:00,2018-01-03 04:00:00
200649,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/03/2018,08:00:00,REGULAR,2446889,27435,TRAM2 R469 00-03-01 RIT-ROOSEVELT,01-03-2018 08:00:00,2018-01-03 08:00:00
200650,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/03/2018,12:00:00,REGULAR,2447230,27435,TRAM2 R469 00-03-01 RIT-ROOSEVELT,01-03-2018 12:00:00,2018-01-03 12:00:00
200651,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/03/2018,16:00:00,REGULAR,2447501,27437,TRAM2 R469 00-03-01 RIT-ROOSEVELT,01-03-2018 16:00:00,2018-01-03 16:00:00
200652,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/03/2018,20:00:00,REGULAR,2447711,27440,TRAM2 R469 00-03-01 RIT-ROOSEVELT,01-03-2018 20:00:00,2018-01-03 20:00:00
200653,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/04/2018,00:00:00,REGULAR,2447795,27443,TRAM2 R469 00-03-01 RIT-ROOSEVELT,01-04-2018 00:00:00,2018-01-04 00:00:00
200654,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/04/2018,04:00:00,REGULAR,2447807,27444,TRAM2 R469 00-03-01 RIT-ROOSEVELT,01-04-2018 04:00:00,2018-01-04 04:00:00
200655,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/04/2018,08:00:00,REGULAR,2447853,27444,TRAM2 R469 00-03-01 RIT-ROOSEVELT,01-04-2018 08:00:00,2018-01-04 08:00:00
200656,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/04/2018,12:00:00,REGULAR,2447967,27449,TRAM2 R469 00-03-01 RIT-ROOSEVELT,01-04-2018 12:00:00,2018-01-04 12:00:00
200657,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/04/2018,16:00:00,REGULAR,2447984,27466,TRAM2 R469 00-03-01 RIT-ROOSEVELT,01-04-2018 16:00:00,2018-01-04 16:00:00
200658,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/04/2018,20:00:00,REGULAR,2448051,27538,TRAM2 R469 00-03-01 RIT-ROOSEVELT,01-04-2018 20:00:00,2018-01-04 20:00:00
200659,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/05/2018,00:00:00,REGULAR,2448078,27545,TRAM2 R469 00-03-01 RIT-ROOSEVELT,01-05-2018 00:00:00,2018-01-05 00:00:00
200660,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/05/2018,04:00:00,REGULAR,2448082,27552,TRAM2 R469 00-03-01 RIT-ROOSEVELT,01-05-2018 04:00:00,2018-01-05 04:00:00
200661,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/05/2018,08:00:00,REGULAR,2448175,27559,TRAM2 R469 00-03-01 RIT-ROOSEVELT,01-05-2018 08:00:00,2018-01-05 08:00:00
200662,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/05/2018,12:00:00,REGULAR,2448484,27568,TRAM2 R469 00-03-01 RIT-ROOSEVELT,01-05-2018 12:00:00,2018-01-05 12:00:00
200663,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/05/2018,16:00:00,REGULAR,2448641,27578,TRAM2 R469 00-03-01 RIT-ROOSEVELT,01-05-2018 16:00:00,2018-01-05 16:00:00
200664,TRAM2,R469,00-03-01,RIT-ROOSEVELT,R,RIT,01/05/2018,20:00:00,REGULAR,2448770,27578,TRAM2 R469 00-03-01 RIT-ROOSEVELT,01-05-2018 20:00:00,2018-01-05 20:00:00

In [3]:
# Checked DESC column to see if RECOVR AUD
df.loc[515:530]

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS,new_key,date_time,parsed_datetime
515,A002,R051,02-06-00,59 ST,NQR456W,BMT,01/05/2018,23:00:00,REGULAR,7362728,156374,A002 R051 02-06-00 59 ST,01-05-2018 23:00:00,2018-01-05 23:00:00
516,A006,R079,00-00-00,5 AV/59 ST,NQRW,BMT,12/30/2017,01:00:00,REGULAR,3171227,5385716,A006 R079 00-00-00 5 AV/59 ST,12-30-2017 01:00:00,2017-12-30 01:00:00
517,A006,R079,00-00-00,5 AV/59 ST,NQRW,BMT,12/30/2017,05:00:00,REGULAR,3171237,5385726,A006 R079 00-00-00 5 AV/59 ST,12-30-2017 05:00:00,2017-12-30 05:00:00
518,A006,R079,00-00-00,5 AV/59 ST,NQRW,BMT,12/30/2017,09:00:00,REGULAR,3171256,5385917,A006 R079 00-00-00 5 AV/59 ST,12-30-2017 09:00:00,2017-12-30 09:00:00
519,A006,R079,00-00-00,5 AV/59 ST,NQRW,BMT,12/30/2017,13:00:00,REGULAR,3171350,5386358,A006 R079 00-00-00 5 AV/59 ST,12-30-2017 13:00:00,2017-12-30 13:00:00
520,A006,R079,00-00-00,5 AV/59 ST,NQRW,BMT,12/30/2017,17:00:00,REGULAR,3171637,5386986,A006 R079 00-00-00 5 AV/59 ST,12-30-2017 17:00:00,2017-12-30 17:00:00
521,A006,R079,00-00-00,5 AV/59 ST,NQRW,BMT,12/30/2017,21:00:00,RECOVR AUD,3172068,5387281,A006 R079 00-00-00 5 AV/59 ST,12-30-2017 21:00:00,2017-12-30 21:00:00
522,A006,R079,00-00-00,5 AV/59 ST,NQRW,BMT,12/31/2017,01:00:00,REGULAR,3172223,5387348,A006 R079 00-00-00 5 AV/59 ST,12-31-2017 01:00:00,2017-12-31 01:00:00
523,A006,R079,00-00-00,5 AV/59 ST,NQRW,BMT,12/31/2017,05:00:00,REGULAR,3172241,5387362,A006 R079 00-00-00 5 AV/59 ST,12-31-2017 05:00:00,2017-12-31 05:00:00
524,A006,R079,00-00-00,5 AV/59 ST,NQRW,BMT,12/31/2017,09:00:00,REGULAR,3172261,5387477,A006 R079 00-00-00 5 AV/59 ST,12-31-2017 09:00:00,2017-12-31 09:00:00
525,A006,R079,00-00-00,5 AV/59 ST,NQRW,BMT,12/31/2017,13:00:00,REGULAR,3172317,5387826,A006 R079 00-00-00 5 AV/59 ST,12-31-2017 13:00:00,2017-12-31 13:00:00
526,A006,R079,00-00-00,5 AV/59 ST,NQRW,BMT,12/31/2017,17:00:00,REGULAR,3172553,5388247,A006 R079 00-00-00 5 AV/59 ST,12-31-2017 17:00:00,2017-12-31 17:00:00
527,A006,R079,00-00-00,5 AV/59 ST,NQRW,BMT,12/31/2017,21:00:00,REGULAR,3172860,5388430,A006 R079 00-00-00 5 AV/59 ST,12-31-2017 21:00:00,2017-12-31 21:00:00
528,A006,R079,00-00-00,5 AV/59 ST,NQRW,BMT,01/01/2018,01:00:00,REGULAR,3172973,5388546,A006 R079 00-00-00 5 AV/59 ST,01-01-2018 01:00:00,2018-01-01 01:00:00
529,A006,R079,00-00-00,5 AV/59 ST,NQRW,BMT,01/01/2018,05:00:00,REGULAR,3173015,5388565,A006 R079 00-00-00 5 AV/59 ST,01-01-2018 05:00:00,2018-01-01 05:00:00
530,A006,R079,00-00-00,5 AV/59 ST,NQRW,BMT,01/01/2018,09:00:00,REGULAR,3173039,5388675,A006 R079 00-00-00 5 AV/59 ST,01-01-2018 09:00:00,2018-01-01 09:00:00

In [4]:
station_id = pd.Categorical(df['new_key']).codes
df['station_id'] = station_id
df.loc[40:60]

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS,new_key,date_time,parsed_datetime,station_id
40,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/05/2018,15:00:00,REGULAR,6469202,2189982,A002 R051 02-00-00 59 ST,01-05-2018 15:00:00,2018-01-05 15:00:00,0
41,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/05/2018,19:00:00,REGULAR,6469927,2190091,A002 R051 02-00-00 59 ST,01-05-2018 19:00:00,2018-01-05 19:00:00,0
42,A002,R051,02-00-00,59 ST,NQR456W,BMT,01/05/2018,23:00:00,REGULAR,6470180,2190117,A002 R051 02-00-00 59 ST,01-05-2018 23:00:00,2018-01-05 23:00:00,0
43,A002,R051,02-00-01,59 ST,NQR456W,BMT,12/30/2017,03:00:00,REGULAR,5808456,1295620,A002 R051 02-00-01 59 ST,12-30-2017 03:00:00,2017-12-30 03:00:00,1
44,A002,R051,02-00-01,59 ST,NQR456W,BMT,12/30/2017,07:00:00,REGULAR,5808463,1295628,A002 R051 02-00-01 59 ST,12-30-2017 07:00:00,2017-12-30 07:00:00,1
45,A002,R051,02-00-01,59 ST,NQR456W,BMT,12/30/2017,11:00:00,REGULAR,5808508,1295676,A002 R051 02-00-01 59 ST,12-30-2017 11:00:00,2017-12-30 11:00:00,1
46,A002,R051,02-00-01,59 ST,NQR456W,BMT,12/30/2017,15:00:00,REGULAR,5808669,1295730,A002 R051 02-00-01 59 ST,12-30-2017 15:00:00,2017-12-30 15:00:00,1
47,A002,R051,02-00-01,59 ST,NQR456W,BMT,12/30/2017,19:00:00,REGULAR,5808922,1295779,A002 R051 02-00-01 59 ST,12-30-2017 19:00:00,2017-12-30 19:00:00,1
48,A002,R051,02-00-01,59 ST,NQR456W,BMT,12/30/2017,23:00:00,REGULAR,5809094,1295803,A002 R051 02-00-01 59 ST,12-30-2017 23:00:00,2017-12-30 23:00:00,1
49,A002,R051,02-00-01,59 ST,NQR456W,BMT,12/31/2017,03:00:00,REGULAR,5809115,1295813,A002 R051 02-00-01 59 ST,12-31-2017 03:00:00,2017-12-31 03:00:00,1
50,A002,R051,02-00-01,59 ST,NQR456W,BMT,12/31/2017,07:00:00,REGULAR,5809123,1295821,A002 R051 02-00-01 59 ST,12-31-2017 07:00:00,2017-12-31 07:00:00,1
51,A002,R051,02-00-01,59 ST,NQR456W,BMT,12/31/2017,11:00:00,REGULAR,5809150,1295848,A002 R051 02-00-01 59 ST,12-31-2017 11:00:00,2017-12-31 11:00:00,1
52,A002,R051,02-00-01,59 ST,NQR456W,BMT,12/31/2017,15:00:00,REGULAR,5809284,1295887,A002 R051 02-00-01 59 ST,12-31-2017 15:00:00,2017-12-31 15:00:00,1
53,A002,R051,02-00-01,59 ST,NQR456W,BMT,12/31/2017,19:00:00,REGULAR,5809472,1295924,A002 R051 02-00-01 59 ST,12-31-2017 19:00:00,2017-12-31 19:00:00,1
54,A002,R051,02-00-01,59 ST,NQR456W,BMT,12/31/2017,23:00:00,REGULAR,5809548,1295935,A002 R051 02-00-01 59 ST,12-31-2017 23:00:00,2017-12-31 23:00:00,1
55,A002,R051,02-00-01,59 ST,NQR456W,BMT,01/01/2018,03:00:00,REGULAR,5809584,1295946,A002 R051 02-00-01 59 ST,01-01-2018 03:00:00,2018-01-01 03:00:00,1
56,A002,R051,02-00-01,59 ST,NQR456W,BMT,01/01/2018,07:00:00,REGULAR,5809593,1295952,A002 R051 02-00-01 59 ST,01-01-2018 07:00:00,2018-01-01 07:00:00,1
57,A002,R051,02-00-01,59 ST,NQR456W,BMT,01/01/2018,11:00:00,REGULAR,5809611,1295984,A002 R051 02-00-01 59 ST,01-01-2018 11:00:00,2018-01-01 11:00:00,1
58,A002,R051,02-00-01,59 ST,NQR456W,BMT,01/01/2018,15:00:00,REGULAR,5809695,1296009,A002 R051 02-00-01 59 ST,01-01-2018 15:00:00,2018-01-01 15:00:00,1
59,A002,R051,02-00-01,59 ST,NQR456W,BMT,01/01/2018,19:00:00,REGULAR,5809848,1296049,A002 R051 02-00-01 59 ST,01-01-2018 19:00:00,2018-01-01 19:00:00,1
60,A002,R051,02-00-01,59 ST,NQR456W,BMT,01/01/2018,23:00:00,REGULAR,5809922,1296066,A002 R051 02-00-01 59 ST,01-01-2018 23:00:00,2018-01-01 23:00:00,1

In [5]:
df.drop(['C/A', 'UNIT', 'SCP', 'DIVISION', 'new_key', 'DATE', 'TIME', 'date_time', 'DESC'], axis = 1, inplace = True)
df.sort_values(['station_id','parsed_datetime'], ascending=[True,True])
df

,STATION,LINENAME,ENTRIES,EXITS,parsed_datetime,station_id
0,59 ST,NQR456W,6463109,2187558,2017-12-30 03:00:00,0
1,59 ST,NQR456W,6463119,2187567,2017-12-30 07:00:00,0
2,59 ST,NQR456W,6463178,2187654,2017-12-30 11:00:00,0
3,59 ST,NQR456W,6463373,2187736,2017-12-30 15:00:00,0
4,59 ST,NQR456W,6463712,2187803,2017-12-30 19:00:00,0
5,59 ST,NQR456W,6463887,2187833,2017-12-30 23:00:00,0
6,59 ST,NQR456W,6463926,2187844,2017-12-31 03:00:00,0
7,59 ST,NQR456W,6463938,2187856,2017-12-31 07:00:00,0
8,59 ST,NQR456W,6463980,2187919,2017-12-31 11:00:00,0
9,59 ST,NQR456W,6464138,2187969,2017-12-31 15:00:00,0
10,59 ST,NQR456W,6464337,2188024,2017-12-31 19:00:00,0
11,59 ST,NQR456W,6464443,2188049,2017-12-31 23:00:00,0
12,59 ST,NQR456W,6464475,2188055,2018-01-01 03:00:00,0
13,59 ST,NQR456W,6464491,2188064,2018-01-01 07:00:00,0
14,59 ST,NQR456W,6464517,2188106,2018-01-01 11:00:00,0
15,59 ST,NQR456W,6464623,2188146,2018-01-01 15:00:00,0
16,59 ST,NQR456W,6464806,2188192,2018-01-01 19:00:00,0
17,59 ST,NQR456W,6464907,2188209,2018-01-01 23:00:00,0
18,59 ST,NQR456W,6464919,2188214,2018-01-02 03:00:00,0
19,59 ST,NQR456W,6464934,2188247,2018-01-02 07:00:00,0
20,59 ST,NQR456W,6465085,2188505,2018-01-02 11:00:00,0
21,59 ST,NQR456W,6465297,2188572,2018-01-02 15:00:00,0
22,59 ST,NQR456W,6466098,2188659,2018-01-02 19:00:00,0
23,59 ST,NQR456W,6466375,2188704,2018-01-02 23:00:00,0
24,59 ST,NQR456W,6466403,2188707,2018-01-03 03:00:00,0
25,59 ST,NQR456W,6466420,2188747,2018-01-03 07:00:00,0
26,59 ST,NQR456W,6466581,2189060,2018-01-03 11:00:00,0
27,59 ST,NQR456W,6466816,2189132,2018-01-03 15:00:00,0
28,59 ST,NQR456W,6467618,2189215,2018-01-03 19:00:00,0
29,59 ST,NQR456W,6467957,2189246,2018-01-03 23:00:00,0
...,...,...,...,...,...,...
200635,RIT-ROOSEVELT,R,2446008,27423,2018-01-01 00:00:00,4711
200636,RIT-ROOSEVELT,R,2446008,27423,2018-01-01 04:00:00,4711
200637,RIT-ROOSEVELT,R,2446008,27423,2018-01-01 08:00:00,4711
200638,RIT-ROOSEVELT,R,2446008,27423,2018-01-01 12:00:00,4711
200639,RIT-ROOSEVELT,R,2446008,27423,2018-01-01 16:00:00,4711
200640,RIT-ROOSEVELT,R,2446008,27423,2018-01-01 20:00:00,4711
200641,RIT-ROOSEVELT,R,2446008,27423,2018-01-02 00:00:00,4711
200642,RIT-ROOSEVELT,R,2446008,27423,2018-01-02 04:00:00,4711
200643,RIT-ROOSEVELT,R,2446008,27423,2018-01-02 08:00:00,4711
200644,RIT-ROOSEVELT,R,2446198,27424,2018-01-02 12:00:00,4711
200645,RIT-ROOSEVELT,R,2446549,27425,2018-01-02 16:00:00,4711
200646,RIT-ROOSEVELT,R,2446730,27432,2018-01-02 20:00:00,4711
200647,RIT-ROOSEVELT,R,2446786,27434,2018-01-03 00:00:00,4711
200648,RIT-ROOSEVELT,R,2446789,27435,2018-01-03 04:00:00,4711
200649,RIT-ROOSEVELT,R,2446889,27435,2018-01-03 08:00:00,4711
200650,RIT-ROOSEVELT,R,2447230,27435,2018-01-03 12:00:00,4711
200651,RIT-ROOSEVELT,R,2447501,27437,2018-01-03 16:00:00,4711
200652,RIT-ROOSEVELT,R,2447711,27440,2018-01-03 20:00:00,4711
200653,RIT-ROOSEVELT,R,2447795,27443,2018-01-04 00:00:00,4711
200654,RIT-ROOSEVELT,R,2447807,27444,2018-01-04 04:00:00,4711
200655,RIT-ROOSEVELT,R,2447853,27444,2018-01-04 08:00:00,4711
200656,RIT-ROOSEVELT,R,2447967,27449,2018-01-04 12:00:00,4711
200657,RIT-ROOSEVELT,R,2447984,27466,2018-01-04 16:00:00,4711
200658,RIT-ROOSEVELT,R,2448051,27538,2018-01-04 20:00:00,4711
200659,RIT-ROOSEVELT,R,2448078,27545,2018-01-05 00:00:00,4711
200660,RIT-ROOSEVELT,R,2448082,27552,2018-01-05 04:00:00,4711
200661,RIT-ROOSEVELT,R,2448175,27559,2018-01-05 08:00:00,4711
200662,RIT-ROOSEVELT,R,2448484,27568,2018-01-05 12:00:00,4711
200663,RIT-ROOSEVELT,R,2448641,27578,2018-01-05 16:00:00,4711
200664,RIT-ROOSEVELT,R,2448770,27578,2018-01-05 20:00:00,4711

In [6]:
df['entry_num'] = abs(df['ENTRIES'].diff())
df['exit_num'] = abs(df['EXITS'].diff())
df['station_diff'] = df['station_id'].diff()
df

,STATION,LINENAME,ENTRIES,EXITS,parsed_datetime,station_id,entry_num,exit_num,station_diff
0,59 ST,NQR456W,6463109,2187558,2017-12-30 03:00:00,0,NaN,NaN,NaN
1,59 ST,NQR456W,6463119,2187567,2017-12-30 07:00:00,0,10.0,9.0,0.0
2,59 ST,NQR456W,6463178,2187654,2017-12-30 11:00:00,0,59.0,87.0,0.0
3,59 ST,NQR456W,6463373,2187736,2017-12-30 15:00:00,0,195.0,82.0,0.0
4,59 ST,NQR456W,6463712,2187803,2017-12-30 19:00:00,0,339.0,67.0,0.0
5,59 ST,NQR456W,6463887,2187833,2017-12-30 23:00:00,0,175.0,30.0,0.0
6,59 ST,NQR456W,6463926,2187844,2017-12-31 03:00:00,0,39.0,11.0,0.0
7,59 ST,NQR456W,6463938,2187856,2017-12-31 07:00:00,0,12.0,12.0,0.0
8,59 ST,NQR456W,6463980,2187919,2017-12-31 11:00:00,0,42.0,63.0,0.0
9,59 ST,NQR456W,6464138,2187969,2017-12-31 15:00:00,0,158.0,50.0,0.0
10,59 ST,NQR456W,6464337,2188024,2017-12-31 19:00:00,0,199.0,55.0,0.0
11,59 ST,NQR456W,6464443,2188049,2017-12-31 23:00:00,0,106.0,25.0,0.0
12,59 ST,NQR456W,6464475,2188055,2018-01-01 03:00:00,0,32.0,6.0,0.0
13,59 ST,NQR456W,6464491,2188064,2018-01-01 07:00:00,0,16.0,9.0,0.0
14,59 ST,NQR456W,6464517,2188106,2018-01-01 11:00:00,0,26.0,42.0,0.0
15,59 ST,NQR456W,6464623,2188146,2018-01-01 15:00:00,0,106.0,40.0,0.0
16,59 ST,NQR456W,6464806,2188192,2018-01-01 19:00:00,0,183.0,46.0,0.0
17,59 ST,NQR456W,6464907,2188209,2018-01-01 23:00:00,0,101.0,17.0,0.0
18,59 ST,NQR456W,6464919,2188214,2018-01-02 03:00:00,0,12.0,5.0,0.0
19,59 ST,NQR456W,6464934,2188247,2018-01-02 07:00:00,0,15.0,33.0,0.0
20,59 ST,NQR456W,6465085,2188505,2018-01-02 11:00:00,0,151.0,258.0,0.0
21,59 ST,NQR456W,6465297,2188572,2018-01-02 15:00:00,0,212.0,67.0,0.0
22,59 ST,NQR456W,6466098,2188659,2018-01-02 19:00:00,0,801.0,87.0,0.0
23,59 ST,NQR456W,6466375,2188704,2018-01-02 23:00:00,0,277.0,45.0,0.0
24,59 ST,NQR456W,6466403,2188707,2018-01-03 03:00:00,0,28.0,3.0,0.0
25,59 ST,NQR456W,6466420,2188747,2018-01-03 07:00:00,0,17.0,40.0,0.0
26,59 ST,NQR456W,6466581,2189060,2018-01-03 11:00:00,0,161.0,313.0,0.0
27,59 ST,NQR456W,6466816,2189132,2018-01-03 15:00:00,0,235.0,72.0,0.0
28,59 ST,NQR456W,6467618,2189215,2018-01-03 19:00:00,0,802.0,83.0,0.0
29,59 ST,NQR456W,6467957,2189246,2018-01-03 23:00:00,0,339.0,31.0,0.0
...,...,...,...,...,...,...,...,...,...
200635,RIT-ROOSEVELT,R,2446008,27423,2018-01-01 00:00:00,4711,0.0,0.0,0.0
200636,RIT-ROOSEVELT,R,2446008,27423,2018-01-01 04:00:00,4711,0.0,0.0,0.0
200637,RIT-ROOSEVELT,R,2446008,27423,2018-01-01 08:00:00,4711,0.0,0.0,0.0
200638,RIT-ROOSEVELT,R,2446008,27423,2018-01-01 12:00:00,4711,0.0,0.0,0.0
200639,RIT-ROOSEVELT,R,2446008,27423,2018-01-01 16:00:00,4711,0.0,0.0,0.0
200640,RIT-ROOSEVELT,R,2446008,27423,2018-01-01 20:00:00,4711,0.0,0.0,0.0
200641,RIT-ROOSEVELT,R,2446008,27423,2018-01-02 00:00:00,4711,0.0,0.0,0.0
200642,RIT-ROOSEVELT,R,2446008,27423,2018-01-02 04:00:00,4711,0.0,0.0,0.0
200643,RIT-ROOSEVELT,R,2446008,27423,2018-01-02 08:00:00,4711,0.0,0.0,0.0
200644,RIT-ROOSEVELT,R,2446198,27424,2018-01-02 12:00:00,4711,190.0,1.0,0.0
200645,RIT-ROOSEVELT,R,2446549,27425,2018-01-02 16:00:00,4711,351.0,1.0,0.0
200646,RIT-ROOSEVELT,R,2446730,27432,2018-01-02 20:00:00,4711,181.0,7.0,0.0
200647,RIT-ROOSEVELT,R,2446786,27434,2018-01-03 00:00:00,4711,56.0,2.0,0.0
200648,RIT-ROOSEVELT,R,2446789,27435,2018-01-03 04:00:00,4711,3.0,1.0,0.0
200649,RIT-ROOSEVELT,R,2446889,27435,2018-01-03 08:00:00,4711,100.0,0.0,0.0
200650,RIT-ROOSEVELT,R,2447230,27435,2018-01-03 12:00:00,4711,341.0,0.0,0.0
200651,RIT-ROOSEVELT,R,2447501,27437,2018-01-03 16:00:00,4711,271.0,2.0,0.0
200652,RIT-ROOSEVELT,R,2447711,27440,2018-01-03 20:00:00,4711,210.0,3.0,0.0
200653,RIT-ROOSEVELT,R,2447795,27443,2018-01-04 00:00:00,4711,84.0,3.0,0.0
200654,RIT-ROOSEVELT,R,2447807,27444,2018-01-04 04:00:00,4711,12.0,1.0,0.0
200655,RIT-ROOSEVELT,R,2447853,27444,2018-01-04 08:00:00,4711,46.0,0.0,0.0
200656,RIT-ROOSEVELT,R,2447967,27449,2018-01-04 12:00:00,4711,114.0,5.0,0.0
200657,RIT-ROOSEVELT,R,2447984,27466,2018-01-04 16:00:00,4711,17.0,17.0,0.0
200658,RIT-ROOSEVELT,R,2448051,27538,2018-01-04 20:00:00,4711,67.0,72.0,0.0
200659,RIT-ROOSEVELT,R,2448078,27545,2018-01-05 00:00:00,4711,27.0,7.0,0.0
200660,RIT-ROOSEVELT,R,2448082,27552,2018-01-05 04:00:00,4711,4.0,7.0,0.0
200661,RIT-ROOSEVELT,R,2448175,27559,2018-01-05 08:00:00,4711,93.0,7.0,0.0
200662,RIT-ROOSEVELT,R,2448484,27568,2018-01-05 12:00:00,4711,309.0,9.0,0.0
200663,RIT-ROOSEVELT,R,2448641,27578,2018-01-05 16:00:00,4711,157.0,10.0,0.0
200664,RIT-ROOSEVELT,R,2448770,27578,2018-01-05 20:00:00,4711,129.0,0.0,0.0

In [7]:
df = df[df.station_diff == 0.0]
df

,STATION,LINENAME,ENTRIES,EXITS,parsed_datetime,station_id,entry_num,exit_num,station_diff
1,59 ST,NQR456W,6463119,2187567,2017-12-30 07:00:00,0,10.0,9.0,0.0
2,59 ST,NQR456W,6463178,2187654,2017-12-30 11:00:00,0,59.0,87.0,0.0
3,59 ST,NQR456W,6463373,2187736,2017-12-30 15:00:00,0,195.0,82.0,0.0
4,59 ST,NQR456W,6463712,2187803,2017-12-30 19:00:00,0,339.0,67.0,0.0
5,59 ST,NQR456W,6463887,2187833,2017-12-30 23:00:00,0,175.0,30.0,0.0
6,59 ST,NQR456W,6463926,2187844,2017-12-31 03:00:00,0,39.0,11.0,0.0
7,59 ST,NQR456W,6463938,2187856,2017-12-31 07:00:00,0,12.0,12.0,0.0
8,59 ST,NQR456W,6463980,2187919,2017-12-31 11:00:00,0,42.0,63.0,0.0
9,59 ST,NQR456W,6464138,2187969,2017-12-31 15:00:00,0,158.0,50.0,0.0
10,59 ST,NQR456W,6464337,2188024,2017-12-31 19:00:00,0,199.0,55.0,0.0
11,59 ST,NQR456W,6464443,2188049,2017-12-31 23:00:00,0,106.0,25.0,0.0
12,59 ST,NQR456W,6464475,2188055,2018-01-01 03:00:00,0,32.0,6.0,0.0
13,59 ST,NQR456W,6464491,2188064,2018-01-01 07:00:00,0,16.0,9.0,0.0
14,59 ST,NQR456W,6464517,2188106,2018-01-01 11:00:00,0,26.0,42.0,0.0
15,59 ST,NQR456W,6464623,2188146,2018-01-01 15:00:00,0,106.0,40.0,0.0
16,59 ST,NQR456W,6464806,2188192,2018-01-01 19:00:00,0,183.0,46.0,0.0
17,59 ST,NQR456W,6464907,2188209,2018-01-01 23:00:00,0,101.0,17.0,0.0
18,59 ST,NQR456W,6464919,2188214,2018-01-02 03:00:00,0,12.0,5.0,0.0
19,59 ST,NQR456W,6464934,2188247,2018-01-02 07:00:00,0,15.0,33.0,0.0
20,59 ST,NQR456W,6465085,2188505,2018-01-02 11:00:00,0,151.0,258.0,0.0
21,59 ST,NQR456W,6465297,2188572,2018-01-02 15:00:00,0,212.0,67.0,0.0
22,59 ST,NQR456W,6466098,2188659,2018-01-02 19:00:00,0,801.0,87.0,0.0
23,59 ST,NQR456W,6466375,2188704,2018-01-02 23:00:00,0,277.0,45.0,0.0
24,59 ST,NQR456W,6466403,2188707,2018-01-03 03:00:00,0,28.0,3.0,0.0
25,59 ST,NQR456W,6466420,2188747,2018-01-03 07:00:00,0,17.0,40.0,0.0
26,59 ST,NQR456W,6466581,2189060,2018-01-03 11:00:00,0,161.0,313.0,0.0
27,59 ST,NQR456W,6466816,2189132,2018-01-03 15:00:00,0,235.0,72.0,0.0
28,59 ST,NQR456W,6467618,2189215,2018-01-03 19:00:00,0,802.0,83.0,0.0
29,59 ST,NQR456W,6467957,2189246,2018-01-03 23:00:00,0,339.0,31.0,0.0
30,59 ST,NQR456W,6467977,2189252,2018-01-04 03:00:00,0,20.0,6.0,0.0
...,...,...,...,...,...,...,...,...,...
200635,RIT-ROOSEVELT,R,2446008,27423,2018-01-01 00:00:00,4711,0.0,0.0,0.0
200636,RIT-ROOSEVELT,R,2446008,27423,2018-01-01 04:00:00,4711,0.0,0.0,0.0
200637,RIT-ROOSEVELT,R,2446008,27423,2018-01-01 08:00:00,4711,0.0,0.0,0.0
200638,RIT-ROOSEVELT,R,2446008,27423,2018-01-01 12:00:00,4711,0.0,0.0,0.0
200639,RIT-ROOSEVELT,R,2446008,27423,2018-01-01 16:00:00,4711,0.0,0.0,0.0
200640,RIT-ROOSEVELT,R,2446008,27423,2018-01-01 20:00:00,4711,0.0,0.0,0.0
200641,RIT-ROOSEVELT,R,2446008,27423,2018-01-02 00:00:00,4711,0.0,0.0,0.0
200642,RIT-ROOSEVELT,R,2446008,27423,2018-01-02 04:00:00,4711,0.0,0.0,0.0
200643,RIT-ROOSEVELT,R,2446008,27423,2018-01-02 08:00:00,4711,0.0,0.0,0.0
200644,RIT-ROOSEVELT,R,2446198,27424,2018-01-02 12:00:00,4711,190.0,1.0,0.0
200645,RIT-ROOSEVELT,R,2446549,27425,2018-01-02 16:00:00,4711,351.0,1.0,0.0
200646,RIT-ROOSEVELT,R,2446730,27432,2018-01-02 20:00:00,4711,181.0,7.0,0.0
200647,RIT-ROOSEVELT,R,2446786,27434,2018-01-03 00:00:00,4711,56.0,2.0,0.0
200648,RIT-ROOSEVELT,R,2446789,27435,2018-01-03 04:00:00,4711,3.0,1.0,0.0
200649,RIT-ROOSEVELT,R,2446889,27435,2018-01-03 08:00:00,4711,100.0,0.0,0.0
200650,RIT-ROOSEVELT,R,2447230,27435,2018-01-03 12:00:00,4711,341.0,0.0,0.0
200651,RIT-ROOSEVELT,R,2447501,27437,2018-01-03 16:00:00,4711,271.0,2.0,0.0
200652,RIT-ROOSEVELT,R,2447711,27440,2018-01-03 20:00:00,4711,210.0,3.0,0.0
200653,RIT-ROOSEVELT,R,2447795,27443,2018-01-04 00:00:00,4711,84.0,3.0,0.0
200654,RIT-ROOSEVELT,R,2447807,27444,2018-01-04 04:00:00,4711,12.0,1.0,0.0
200655,RIT-ROOSEVELT,R,2447853,27444,2018-01-04 08:00:00,4711,46.0,0.0,0.0
200656,RIT-ROOSEVELT,R,2447967,27449,2018-01-04 12:00:00,4711,114.0,5.0,0.0
200657,RIT-ROOSEVELT,R,2447984,27466,2018-01-04 16:00:00,4711,17.0,17.0,0.0
200658,RIT-ROOSEVELT,R,2448051,27538,2018-01-04 20:00:00,4711,67.0,72.0,0.0
200659,RIT-ROOSEVELT,R,2448078,27545,2018-01-05 00:00:00,4711,27.0,7.0,0.0
200660,RIT-ROOSEVELT,R,2448082,27552,2018-01-05 04:00:00,4711,4.0,7.0,0.0
200661,RIT-ROOSEVELT,R,2448175,27559,2018-01-05 08:00:00,4711,93.0,7.0,0.0
200662,RIT-ROOSEVELT,R,2448484,27568,2018-01-05 12:00:00,4711,309.0,9.0,0.0
200663,RIT-ROOSEVELT,R,2448641,27578,2018-01-05 16:00:00,4711,157.0,10.0,0.0
200664,RIT-ROOSEVELT,R,2448770,27578,2018-01-05 20:00:00,4711,129.0,0.0,0.0

In [8]:
df.loc[30:50]

,STATION,LINENAME,ENTRIES,EXITS,parsed_datetime,station_id,entry_num,exit_num,station_diff
30,59 ST,NQR456W,6467977,2189252,2018-01-04 03:00:00,0,20.0,6.0,0.0
31,59 ST,NQR456W,6467990,2189276,2018-01-04 07:00:00,0,13.0,24.0,0.0
32,59 ST,NQR456W,6468094,2189471,2018-01-04 11:00:00,0,104.0,195.0,0.0
33,59 ST,NQR456W,6468105,2189478,2018-01-04 11:20:58,0,11.0,7.0,0.0
34,59 ST,NQR456W,6468315,2189521,2018-01-04 15:00:00,0,210.0,43.0,0.0
35,59 ST,NQR456W,6468683,2189575,2018-01-04 19:00:00,0,368.0,54.0,0.0
36,59 ST,NQR456W,6468797,2189588,2018-01-04 23:00:00,0,114.0,13.0,0.0
37,59 ST,NQR456W,6468809,2189590,2018-01-05 03:00:00,0,12.0,2.0,0.0
38,59 ST,NQR456W,6468825,2189610,2018-01-05 07:00:00,0,16.0,20.0,0.0
39,59 ST,NQR456W,6468964,2189912,2018-01-05 11:00:00,0,139.0,302.0,0.0
40,59 ST,NQR456W,6469202,2189982,2018-01-05 15:00:00,0,238.0,70.0,0.0
41,59 ST,NQR456W,6469927,2190091,2018-01-05 19:00:00,0,725.0,109.0,0.0
42,59 ST,NQR456W,6470180,2190117,2018-01-05 23:00:00,0,253.0,26.0,0.0
44,59 ST,NQR456W,5808463,1295628,2017-12-30 07:00:00,1,7.0,8.0,0.0
45,59 ST,NQR456W,5808508,1295676,2017-12-30 11:00:00,1,45.0,48.0,0.0
46,59 ST,NQR456W,5808669,1295730,2017-12-30 15:00:00,1,161.0,54.0,0.0
47,59 ST,NQR456W,5808922,1295779,2017-12-30 19:00:00,1,253.0,49.0,0.0
48,59 ST,NQR456W,5809094,1295803,2017-12-30 23:00:00,1,172.0,24.0,0.0
49,59 ST,NQR456W,5809115,1295813,2017-12-31 03:00:00,1,21.0,10.0,0.0
50,59 ST,NQR456W,5809123,1295821,2017-12-31 07:00:00,1,8.0,8.0,0.0

In [9]:
df['time'] = df.apply(lambda row: row.parsed_datetime.time(), axis=1)

/Users/matiasbeeck/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [10]:
# df['weekday'] = df['parsed_datetime'].dt.weekday
# df['weekday_bin'] = df.apply(lambda row: 1 if df.weekday < 5 else 0, axis=1)

df['Weekday'] = df['parsed_datetime'].dt.weekday
df['Weekend'] = 0
df['Weekend'] = df['Weekday'] >= 5
df.drop('Weekday', axis=1, inplace = True)
df

/Users/matiasbeeck/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/Users/matiasbeeck/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
/Users/matiasbeeck/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/matiasbeeck/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

,STATION,LINENAME,ENTRIES,EXITS,parsed_datetime,station_id,entry_num,exit_num,station_diff,time,Weekend
1,59 ST,NQR456W,6463119,2187567,2017-12-30 07:00:00,0,10.0,9.0,0.0,07:00:00,True
2,59 ST,NQR456W,6463178,2187654,2017-12-30 11:00:00,0,59.0,87.0,0.0,11:00:00,True
3,59 ST,NQR456W,6463373,2187736,2017-12-30 15:00:00,0,195.0,82.0,0.0,15:00:00,True
4,59 ST,NQR456W,6463712,2187803,2017-12-30 19:00:00,0,339.0,67.0,0.0,19:00:00,True
5,59 ST,NQR456W,6463887,2187833,2017-12-30 23:00:00,0,175.0,30.0,0.0,23:00:00,True
6,59 ST,NQR456W,6463926,2187844,2017-12-31 03:00:00,0,39.0,11.0,0.0,03:00:00,True
7,59 ST,NQR456W,6463938,2187856,2017-12-31 07:00:00,0,12.0,12.0,0.0,07:00:00,True
8,59 ST,NQR456W,6463980,2187919,2017-12-31 11:00:00,0,42.0,63.0,0.0,11:00:00,True
9,59 ST,NQR456W,6464138,2187969,2017-12-31 15:00:00,0,158.0,50.0,0.0,15:00:00,True
10,59 ST,NQR456W,6464337,2188024,2017-12-31 19:00:00,0,199.0,55.0,0.0,19:00:00,True
11,59 ST,NQR456W,6464443,2188049,2017-12-31 23:00:00,0,106.0,25.0,0.0,23:00:00,True
12,59 ST,NQR456W,6464475,2188055,2018-01-01 03:00:00,0,32.0,6.0,0.0,03:00:00,False
13,59 ST,NQR456W,6464491,2188064,2018-01-01 07:00:00,0,16.0,9.0,0.0,07:00:00,False
14,59 ST,NQR456W,6464517,2188106,2018-01-01 11:00:00,0,26.0,42.0,0.0,11:00:00,False
15,59 ST,NQR456W,6464623,2188146,2018-01-01 15:00:00,0,106.0,40.0,0.0,15:00:00,False
16,59 ST,NQR456W,6464806,2188192,2018-01-01 19:00:00,0,183.0,46.0,0.0,19:00:00,False
17,59 ST,NQR456W,6464907,2188209,2018-01-01 23:00:00,0,101.0,17.0,0.0,23:00:00,False
18,59 ST,NQR456W,6464919,2188214,2018-01-02 03:00:00,0,12.0,5.0,0.0,03:00:00,False
19,59 ST,NQR456W,6464934,2188247,2018-01-02 07:00:00,0,15.0,33.0,0.0,07:00:00,False
20,59 ST,NQR456W,6465085,2188505,2018-01-02 11:00:00,0,151.0,258.0,0.0,11:00:00,False
21,59 ST,NQR456W,6465297,2188572,2018-01-02 15:00:00,0,212.0,67.0,0.0,15:00:00,False
22,59 ST,NQR456W,6466098,2188659,2018-01-02 19:00:00,0,801.0,87.0,0.0,19:00:00,False
23,59 ST,NQR456W,6466375,2188704,2018-01-02 23:00:00,0,277.0,45.0,0.0,23:00:00,False
24,59 ST,NQR456W,6466403,2188707,2018-01-03 03:00:00,0,28.0,3.0,0.0,03:00:00,False
25,59 ST,NQR456W,6466420,2188747,2018-01-03 07:00:00,0,17.0,40.0,0.0,07:00:00,False
26,59 ST,NQR456W,6466581,2189060,2018-01-03 11:00:00,0,161.0,313.0,0.0,11:00:00,False
27,59 ST,NQR456W,6466816,2189132,2018-01-03 15:00:00,0,235.0,72.0,0.0,15:00:00,False
28,59 ST,NQR456W,6467618,2189215,2018-01-03 19:00:00,0,802.0,83.0,0.0,19:00:00,False
29,59 ST,NQR456W,6467957,2189246,2018-01-03 23:00:00,0,339.0,31.0,0.0,23:00:00,False
30,59 ST,NQR456W,6467977,2189252,2018-01-04 03:00:00,0,20.0,6.0,0.0,03:00:00,False
...,...,...,...,...,...,...,...,...,...,...,...
200635,RIT-ROOSEVELT,R,2446008,27423,2018-01-01 00:00:00,4711,0.0,0.0,0.0,00:00:00,False
200636,RIT-ROOSEVELT,R,2446008,27423,2018-01-01 04:00:00,4711,0.0,0.0,0.0,04:00:00,False
200637,RIT-ROOSEVELT,R,2446008,27423,2018-01-01 08:00:00,4711,0.0,0.0,0.0,08:00:00,False
200638,RIT-ROOSEVELT,R,2446008,27423,2018-01-01 12:00:00,4711,0.0,0.0,0.0,12:00:00,False
200639,RIT-ROOSEVELT,R,2446008,27423,2018-01-01 16:00:00,4711,0.0,0.0,0.0,16:00:00,False
200640,RIT-ROOSEVELT,R,2446008,27423,2018-01-01 20:00:00,4711,0.0,0.0,0.0,20:00:00,False
200641,RIT-ROOSEVELT,R,2446008,27423,2018-01-02 00:00:00,4711,0.0,0.0,0.0,00:00:00,False
200642,RIT-ROOSEVELT,R,2446008,27423,2018-01-02 04:00:00,4711,0.0,0.0,0.0,04:00:00,False
200643,RIT-ROOSEVELT,R,2446008,27423,2018-01-02 08:00:00,4711,0.0,0.0,0.0,08:00:00,False
200644,RIT-ROOSEVELT,R,2446198,27424,2018-01-02 12:00:00,4711,190.0,1.0,0.0,12:00:00,False
200645,RIT-ROOSEVELT,R,2446549,27425,2018-01-02 16:00:00,4711,351.0,1.0,0.0,16:00:00,False
200646,RIT-ROOSEVELT,R,2446730,27432,2018-01-02 20:00:00,4711,181.0,7.0,0.0,20:00:00,False
200647,RIT-ROOSEVELT,R,2446786,27434,2018-01-03 00:00:00,4711,56.0,2.0,0.0,00:00:00,False
200648,RIT-ROOSEVELT,R,2446789,27435,2018-01-03 04:00:00,4711,3.0,1.0,0.0,04:00:00,False
200649,RIT-ROOSEVELT,R,2446889,27435,2018-01-03 08:00:00,4711,100.0,0.0,0.0,08:00:00,False
200650,RIT-ROOSEVELT,R,2447230,27435,2018-01-03 12:00:00,4711,341.0,0.0,0.0,12:00:00,False
200651,RIT-ROOSEVELT,R,2447501,27437,2018-01-03 16:00:00,4711,271.0,2.0,0.0,16:00:00,False
200652,RIT-ROOSEVELT,R,2447711,27440,2018-01-03 20:00:00,4711,210.0,3.0,0.0,20:00:00,False
200653,RIT-ROOSEVELT,R,2447795,27443,2018-01-04 00:00:00,4711,84.0,3.0,0.0,00:00:00,False
200654,RIT-ROOSEVELT,R,2447807,27444,2018-01-04 04:00:00,4711,12.0,1.0,0.0,04:00:00,False
200655,RIT-ROOSEVELT,R,2447853,27444,2018-01-04 08:00:00,4711,46.0,0.0,0.0,08:00:00,False
200656,RIT-ROOSEVELT,R,2447967,27449,2018-01-04 12:00:00,4711,114.0,5.0,0.0,12:00:00,False
200657,RIT-ROOSEVELT,R,2447984,27466,2018-01-04 16:00:00,4711,17.0,17.0,0.0,16:00:00,False
200658,RIT-ROOSEVELT,R,2448051,27538,2018-01-04 20:00:00,4711,67.0,72.0,0.0,20:00:00,False
200659,RIT-ROOSEVELT,R,2448078,27545,2018-01-05 00:00:00,4711,27.0,7.0,0.0,00:00:00,False
200660,RIT-ROOSEVELT,R,2448082,27552,2018-01-05 04:00:00,4711,4.0,7.0,0.0,04:00:00,False
200661,RIT-ROOSEVELT,R,2448175,27559,2018-01-05 08:00:00,4711,93.0,7.0,0.0,08:00:00,False
200662,RIT-ROOSEVELT,R,2448484,27568,2018-01-05 12:00:00,4711,309.0,9.0,0.0,12:00:00,False
200663,RIT-ROOSEVELT,R,2448641,27578,2018-01-05 16:00:00,4711,157.0,10.0,0.0,16:00:00,False
200664,RIT-ROOSEVELT,R,2448770,27578,2018-01-05 20:00:00,4711,129.0,0.0,0.0,20:00:00,False

In [11]:
df = df.reset_index()
df[df.STATION == 'BROOKLYN BRIDGE'].sort_values(by=['entry_num'])
df.iloc[145435:145440]

,index,STATION,LINENAME,ENTRIES,EXITS,parsed_datetime,station_id,entry_num,exit_num,station_diff,time,Weekend
145435,148934,BROOKLYN BRIDGE,456JZ,1859727258,1007602501,2017-12-31 07:00:00,3498,0.0,5.0,0.0,07:00:00,True
145436,148935,BROOKLYN BRIDGE,456JZ,1859727197,1007602533,2017-12-31 11:00:00,3498,61.0,32.0,0.0,11:00:00,True
145437,148936,BROOKLYN BRIDGE,456JZ,1859726847,1007602618,2017-12-31 15:00:00,3498,350.0,85.0,0.0,15:00:00,True
145438,148937,BROOKLYN BRIDGE,456JZ,1859726489,1007602664,2017-12-31 19:00:00,3498,358.0,46.0,0.0,19:00:00,True
145439,148938,BROOKLYN BRIDGE,456JZ,1859726403,1007602700,2017-12-31 23:00:00,3498,86.0,36.0,0.0,23:00:00,True

In [12]:
df.groupby(['STATION'])[['entry_num']].sum().sort_values(by=['entry_num'])

                  entry_num
STATION
NEWARK HM HE            0.0
BEACH 105 ST          865.0
BROAD CHANNEL        1106.0
BEACH 98 ST          1877.0
SENECA AVE           2470.0
ROCKAWAY PARK B      2698.0
BEACH 44 ST          3084.0
TOMPKINSVILLE        3275.0
AVENUE I             3576.0
AQUEDUCT N.COND      3768.0
BEACH 90 ST          3772.0
BEACH 36 ST          3947.0
E 143/ST MARY'S      4376.0
BOTANIC GARDEN       5438.0
AVENUE P             6009.0
NEPTUNE AV           6603.0
CYPRESS HILLS        6630.0
121 ST               7214.0
BEACH 25 ST          7844.0
AVENUE N             7930.0
ATLANTIC AV          8100.0
215 ST               8160.0
MIDDLETOWN RD        8441.0
WHITLOCK AV          8492.0
W 8 ST-AQUARIUM      8502.0
21 ST                8633.0
AQUEDUCT RACETR      8996.0
JUNIUS ST            9072.0
BEACH 67 ST          9260.0
FOREST AVE           9464.0
...                     ...
42 ST-BRYANT PK    193199.0
ATL AV-BARCLAY     212305.0
CITY / BUS         216785.0
28 ST              220484.0
72 ST              225715.0
CHAMBERS ST        228940.0
JKSN HT-ROOSVLT    235698.0
50 ST              250676.0
14 ST              260309.0
FLUSHING-MAIN      265395.0
96 ST              279024.0
59 ST              317446.0
47-50 STS ROCK     317789.0
59 ST COLUMBUS     324675.0
CANAL ST           337346.0
125 ST             353776.0
PATH NEW WTC       371192.0
86 ST              400994.0
14 ST-UNION SQ     445831.0
TIMES SQ-42 ST     460115.0
23 ST              480621.0
FULTON ST          519782.0
34 ST-HERALD SQ    610512.0
BROOKLYN BRIDGE    619937.0
GRD CNTRL-42 ST    676770.0
RIT-MANHATTAN     1709581.0
SUTTER AV-RUTLD   2651702.0
145 ST           16712433.0
34 ST-PENN STA   26508166.0
42 ST-PORT AUTH  98102194.0

[373 rows x 1 columns]